// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: doctors/v1/seo.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetDoctorSeoDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDoctorSeoDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDoctorSeoDataRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDoctorSeoDataRequestMultiError, or nil if none found.
func (m *GetDoctorSeoDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDoctorSeoDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DoctorSlug

	if len(errors) > 0 {
		return GetDoctorSeoDataRequestMultiError(errors)
	}

	return nil
}

// GetDoctorSeoDataRequestMultiError is an error wrapping multiple validation
// errors returned by GetDoctorSeoDataRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDoctorSeoDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDoctorSeoDataRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDoctorSeoDataRequestMultiError) AllErrors() []error { return m }

// GetDoctorSeoDataRequestValidationError is the validation error returned by
// GetDoctorSeoDataRequest.Validate if the designated constraints aren't met.
type GetDoctorSeoDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDoctorSeoDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDoctorSeoDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDoctorSeoDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDoctorSeoDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDoctorSeoDataRequestValidationError) ErrorName() string {
	return "GetDoctorSeoDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDoctorSeoDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDoctorSeoDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDoctorSeoDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDoctorSeoDataRequestValidationError{}

// Validate checks the field values on GetDoctorSeoDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDoctorSeoDataResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDoctorSeoDataResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDoctorSeoDataResponseMultiError, or nil if none found.
func (m *GetDoctorSeoDataResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDoctorSeoDataResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Description

	if len(errors) > 0 {
		return GetDoctorSeoDataResponseMultiError(errors)
	}

	return nil
}

// GetDoctorSeoDataResponseMultiError is an error wrapping multiple validation
// errors returned by GetDoctorSeoDataResponse.ValidateAll() if the designated
// constraints aren't met.
type GetDoctorSeoDataResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDoctorSeoDataResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDoctorSeoDataResponseMultiError) AllErrors() []error { return m }

// GetDoctorSeoDataResponseValidationError is the validation error returned by
// GetDoctorSeoDataResponse.Validate if the designated constraints aren't met.
type GetDoctorSeoDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDoctorSeoDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDoctorSeoDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDoctorSeoDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDoctorSeoDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDoctorSeoDataResponseValidationError) ErrorName() string {
	return "GetDoctorSeoDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDoctorSeoDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDoctorSeoDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDoctorSeoDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDoctorSeoDataResponseValidationError{}
