// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: doctors/v1/seo.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Seo_GetDoctorSeoData_FullMethodName      = "/doctor.v1.Seo/GetDoctorSeoData"
	Seo_GetFreelancersSeoData_FullMethodName = "/doctor.v1.Seo/GetFreelancersSeoData"
)

// SeoClient is the client API for Seo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeoClient interface {
	GetDoctorSeoData(ctx context.Context, in *GetDoctorSeoDataRequest, opts ...grpc.CallOption) (*GetDoctorSeoDataResponse, error)
	GetFreelancersSeoData(ctx context.Context, in *GetFreelancersSeoDataRequest, opts ...grpc.CallOption) (*GetFreelancersSeoDataResponse, error)
}

type seoClient struct {
	cc grpc.ClientConnInterface
}

func NewSeoClient(cc grpc.ClientConnInterface) SeoClient {
	return &seoClient{cc}
}

func (c *seoClient) GetDoctorSeoData(ctx context.Context, in *GetDoctorSeoDataRequest, opts ...grpc.CallOption) (*GetDoctorSeoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorSeoDataResponse)
	err := c.cc.Invoke(ctx, Seo_GetDoctorSeoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seoClient) GetFreelancersSeoData(ctx context.Context, in *GetFreelancersSeoDataRequest, opts ...grpc.CallOption) (*GetFreelancersSeoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancersSeoDataResponse)
	err := c.cc.Invoke(ctx, Seo_GetFreelancersSeoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeoServer is the server API for Seo service.
// All implementations must embed UnimplementedSeoServer
// for forward compatibility.
type SeoServer interface {
	GetDoctorSeoData(context.Context, *GetDoctorSeoDataRequest) (*GetDoctorSeoDataResponse, error)
	GetFreelancersSeoData(context.Context, *GetFreelancersSeoDataRequest) (*GetFreelancersSeoDataResponse, error)
	mustEmbedUnimplementedSeoServer()
}

// UnimplementedSeoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeoServer struct{}

func (UnimplementedSeoServer) GetDoctorSeoData(context.Context, *GetDoctorSeoDataRequest) (*GetDoctorSeoDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDoctorSeoData not implemented")
}
func (UnimplementedSeoServer) GetFreelancersSeoData(context.Context, *GetFreelancersSeoDataRequest) (*GetFreelancersSeoDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreelancersSeoData not implemented")
}
func (UnimplementedSeoServer) mustEmbedUnimplementedSeoServer() {}
func (UnimplementedSeoServer) testEmbeddedByValue()             {}

// UnsafeSeoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeoServer will
// result in compilation errors.
type UnsafeSeoServer interface {
	mustEmbedUnimplementedSeoServer()
}

func RegisterSeoServer(s grpc.ServiceRegistrar, srv SeoServer) {
	// If the following call pancis, it indicates UnimplementedSeoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Seo_ServiceDesc, srv)
}

func _Seo_GetDoctorSeoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorSeoDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeoServer).GetDoctorSeoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seo_GetDoctorSeoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeoServer).GetDoctorSeoData(ctx, req.(*GetDoctorSeoDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seo_GetFreelancersSeoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancersSeoDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeoServer).GetFreelancersSeoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seo_GetFreelancersSeoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeoServer).GetFreelancersSeoData(ctx, req.(*GetFreelancersSeoDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Seo_ServiceDesc is the grpc.ServiceDesc for Seo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doctor.v1.Seo",
	HandlerType: (*SeoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDoctorSeoData",
			Handler:    _Seo_GetDoctorSeoData_Handler,
		},
		{
			MethodName: "GetFreelancersSeoData",
			Handler:    _Seo_GetFreelancersSeoData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doctors/v1/seo.proto",
}
