// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: admin/freelancers/city/v1/freelancer_city.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FreelancerAdminCityService_GetCities_FullMethodName    = "/admin.freelancers.city.v1.FreelancerAdminCityService/GetCities"
	FreelancerAdminCityService_SearchCities_FullMethodName = "/admin.freelancers.city.v1.FreelancerAdminCityService/SearchCities"
	FreelancerAdminCityService_CreateCity_FullMethodName   = "/admin.freelancers.city.v1.FreelancerAdminCityService/CreateCity"
)

// FreelancerAdminCityServiceClient is the client API for FreelancerAdminCityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------- Сервис по работе с городами докторов ---------------
type FreelancerAdminCityServiceClient interface {
	GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error)
	SearchCities(ctx context.Context, in *SearchCitiesRequest, opts ...grpc.CallOption) (*SearchCitiesResponse, error)
	CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityResponse, error)
}

type freelancerAdminCityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFreelancerAdminCityServiceClient(cc grpc.ClientConnInterface) FreelancerAdminCityServiceClient {
	return &freelancerAdminCityServiceClient{cc}
}

func (c *freelancerAdminCityServiceClient) GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCitiesResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminCityService_GetCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminCityServiceClient) SearchCities(ctx context.Context, in *SearchCitiesRequest, opts ...grpc.CallOption) (*SearchCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCitiesResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminCityService_SearchCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminCityServiceClient) CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCityResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminCityService_CreateCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreelancerAdminCityServiceServer is the server API for FreelancerAdminCityService service.
// All implementations should embed UnimplementedFreelancerAdminCityServiceServer
// for forward compatibility.
//
// -------------- Сервис по работе с городами докторов ---------------
type FreelancerAdminCityServiceServer interface {
	GetCities(context.Context, *GetCitiesRequest) (*GetCitiesResponse, error)
	SearchCities(context.Context, *SearchCitiesRequest) (*SearchCitiesResponse, error)
	CreateCity(context.Context, *CreateCityRequest) (*CreateCityResponse, error)
}

// UnimplementedFreelancerAdminCityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFreelancerAdminCityServiceServer struct{}

func (UnimplementedFreelancerAdminCityServiceServer) GetCities(context.Context, *GetCitiesRequest) (*GetCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCities not implemented")
}
func (UnimplementedFreelancerAdminCityServiceServer) SearchCities(context.Context, *SearchCitiesRequest) (*SearchCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCities not implemented")
}
func (UnimplementedFreelancerAdminCityServiceServer) CreateCity(context.Context, *CreateCityRequest) (*CreateCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCity not implemented")
}
func (UnimplementedFreelancerAdminCityServiceServer) testEmbeddedByValue() {}

// UnsafeFreelancerAdminCityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreelancerAdminCityServiceServer will
// result in compilation errors.
type UnsafeFreelancerAdminCityServiceServer interface {
	mustEmbedUnimplementedFreelancerAdminCityServiceServer()
}

func RegisterFreelancerAdminCityServiceServer(s grpc.ServiceRegistrar, srv FreelancerAdminCityServiceServer) {
	// If the following call panics, it indicates UnimplementedFreelancerAdminCityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FreelancerAdminCityService_ServiceDesc, srv)
}

func _FreelancerAdminCityService_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminCityServiceServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminCityService_GetCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminCityServiceServer).GetCities(ctx, req.(*GetCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminCityService_SearchCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminCityServiceServer).SearchCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminCityService_SearchCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminCityServiceServer).SearchCities(ctx, req.(*SearchCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminCityService_CreateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminCityServiceServer).CreateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminCityService_CreateCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminCityServiceServer).CreateCity(ctx, req.(*CreateCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FreelancerAdminCityService_ServiceDesc is the grpc.ServiceDesc for FreelancerAdminCityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FreelancerAdminCityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.freelancers.city.v1.FreelancerAdminCityService",
	HandlerType: (*FreelancerAdminCityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCities",
			Handler:    _FreelancerAdminCityService_GetCities_Handler,
		},
		{
			MethodName: "SearchCities",
			Handler:    _FreelancerAdminCityService_SearchCities_Handler,
		},
		{
			MethodName: "CreateCity",
			Handler:    _FreelancerAdminCityService_CreateCity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/freelancers/city/v1/freelancer_city.proto",
}
