// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: admin/doctors/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoctorAdminService_GetDoctors_FullMethodName                 = "/DoctorAdminService/GetDoctors"
	DoctorAdminService_GetDoctorsByIDs_FullMethodName            = "/DoctorAdminService/GetDoctorsByIDs"
	DoctorAdminService_SortDoctors_FullMethodName                = "/DoctorAdminService/SortDoctors"
	DoctorAdminService_SearchDoctors_FullMethodName              = "/DoctorAdminService/SearchDoctors"
	DoctorAdminService_GetDoctorByID_FullMethodName              = "/DoctorAdminService/GetDoctorByID"
	DoctorAdminService_UpdateDoctor_FullMethodName               = "/DoctorAdminService/UpdateDoctor"
	DoctorAdminService_DeleteDoctor_FullMethodName               = "/DoctorAdminService/DeleteDoctor"
	DoctorAdminService_ActivateDoctor_FullMethodName             = "/DoctorAdminService/ActivateDoctor"
	DoctorAdminService_DeactivateDoctor_FullMethodName           = "/DoctorAdminService/DeactivateDoctor"
	DoctorAdminService_SaveDoctorPhoto_FullMethodName            = "/DoctorAdminService/SaveDoctorPhoto"
	DoctorAdminService_AddAdditionalCity_FullMethodName          = "/DoctorAdminService/AddAdditionalCity"
	DoctorAdminService_AddAdditionalSpeciality_FullMethodName    = "/DoctorAdminService/AddAdditionalSpeciality"
	DoctorAdminService_DeleteAdditionalCity_FullMethodName       = "/DoctorAdminService/DeleteAdditionalCity"
	DoctorAdminService_DeleteAdditionalSpeciality_FullMethodName = "/DoctorAdminService/DeleteAdditionalSpeciality"
	DoctorAdminService_UpdateSubscribers_FullMethodName          = "/DoctorAdminService/UpdateSubscribers"
)

// DoctorAdminServiceClient is the client API for DoctorAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------- Сервис по работе с докторов ---------------
type DoctorAdminServiceClient interface {
	GetDoctors(ctx context.Context, in *GetDoctorsRequest, opts ...grpc.CallOption) (*GetDoctorsResponse, error)
	GetDoctorsByIDs(ctx context.Context, in *GetDoctorsByIDsRequest, opts ...grpc.CallOption) (*GetDoctorsByIDsResponse, error)
	SortDoctors(ctx context.Context, in *SortDoctorsRequest, opts ...grpc.CallOption) (*SortDoctorsResponse, error)
	// todo подумать тоже, а надо ли тут эту сортировку
	//
	//	rpc FilterDoctors(FilterDoctorsRequest) returns (FilterDoctorsResponse) {
	//	    option (google.api.http) = {
	//	        post: "/api/v1/admin/doctors/filter"
	//	        body: "*"
	//	    };
	//	    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
	//	        summary: "Фильтрация врачей"
	//	    };
	//	}
	SearchDoctors(ctx context.Context, in *SearchDoctorsRequest, opts ...grpc.CallOption) (*SearchDoctorsResponse, error)
	GetDoctorByID(ctx context.Context, in *GetDoctorByIDRequest, opts ...grpc.CallOption) (*GetDoctorByIDResponse, error)
	UpdateDoctor(ctx context.Context, in *UpdateDoctorRequest, opts ...grpc.CallOption) (*UpdateDoctorResponse, error)
	DeleteDoctor(ctx context.Context, in *DeleteDoctorRequest, opts ...grpc.CallOption) (*DeleteDoctorResponse, error)
	ActivateDoctor(ctx context.Context, in *ActivateDoctorRequest, opts ...grpc.CallOption) (*ActivateDoctorResponse, error)
	DeactivateDoctor(ctx context.Context, in *DeactivateDoctorRequest, opts ...grpc.CallOption) (*DeactivateDoctorResponse, error)
	SaveDoctorPhoto(ctx context.Context, in *SaveDoctorPhotoRequest, opts ...grpc.CallOption) (*SaveDoctorPhotoResponse, error)
	AddAdditionalCity(ctx context.Context, in *AddDoctorAdditionalCityRequest, opts ...grpc.CallOption) (*AddDoctorAdditionalCityResponse, error)
	AddAdditionalSpeciality(ctx context.Context, in *AddDoctorAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddDoctorAdditionalSpecialityResponse, error)
	DeleteAdditionalCity(ctx context.Context, in *DeleteDoctorAdditionalCityRequest, opts ...grpc.CallOption) (*DeleteDoctorAdditionalCityResponse, error)
	DeleteAdditionalSpeciality(ctx context.Context, in *DeleteDoctorAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteDoctorAdditionalSpecialityResponse, error)
	UpdateSubscribers(ctx context.Context, in *UpdateSubscribersRequest, opts ...grpc.CallOption) (*UpdateSubscribersResponse, error)
}

type doctorAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorAdminServiceClient(cc grpc.ClientConnInterface) DoctorAdminServiceClient {
	return &doctorAdminServiceClient{cc}
}

func (c *doctorAdminServiceClient) GetDoctors(ctx context.Context, in *GetDoctorsRequest, opts ...grpc.CallOption) (*GetDoctorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_GetDoctors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) GetDoctorsByIDs(ctx context.Context, in *GetDoctorsByIDsRequest, opts ...grpc.CallOption) (*GetDoctorsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsByIDsResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_GetDoctorsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) SortDoctors(ctx context.Context, in *SortDoctorsRequest, opts ...grpc.CallOption) (*SortDoctorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortDoctorsResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_SortDoctors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) SearchDoctors(ctx context.Context, in *SearchDoctorsRequest, opts ...grpc.CallOption) (*SearchDoctorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDoctorsResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_SearchDoctors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) GetDoctorByID(ctx context.Context, in *GetDoctorByIDRequest, opts ...grpc.CallOption) (*GetDoctorByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorByIDResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_GetDoctorByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) UpdateDoctor(ctx context.Context, in *UpdateDoctorRequest, opts ...grpc.CallOption) (*UpdateDoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDoctorResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_UpdateDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) DeleteDoctor(ctx context.Context, in *DeleteDoctorRequest, opts ...grpc.CallOption) (*DeleteDoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDoctorResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_DeleteDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) ActivateDoctor(ctx context.Context, in *ActivateDoctorRequest, opts ...grpc.CallOption) (*ActivateDoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateDoctorResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_ActivateDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) DeactivateDoctor(ctx context.Context, in *DeactivateDoctorRequest, opts ...grpc.CallOption) (*DeactivateDoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateDoctorResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_DeactivateDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) SaveDoctorPhoto(ctx context.Context, in *SaveDoctorPhotoRequest, opts ...grpc.CallOption) (*SaveDoctorPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDoctorPhotoResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_SaveDoctorPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) AddAdditionalCity(ctx context.Context, in *AddDoctorAdditionalCityRequest, opts ...grpc.CallOption) (*AddDoctorAdditionalCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDoctorAdditionalCityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_AddAdditionalCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) AddAdditionalSpeciality(ctx context.Context, in *AddDoctorAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddDoctorAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDoctorAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_AddAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) DeleteAdditionalCity(ctx context.Context, in *DeleteDoctorAdditionalCityRequest, opts ...grpc.CallOption) (*DeleteDoctorAdditionalCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDoctorAdditionalCityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_DeleteAdditionalCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) DeleteAdditionalSpeciality(ctx context.Context, in *DeleteDoctorAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteDoctorAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDoctorAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_DeleteAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminServiceClient) UpdateSubscribers(ctx context.Context, in *UpdateSubscribersRequest, opts ...grpc.CallOption) (*UpdateSubscribersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscribersResponse)
	err := c.cc.Invoke(ctx, DoctorAdminService_UpdateSubscribers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorAdminServiceServer is the server API for DoctorAdminService service.
// All implementations should embed UnimplementedDoctorAdminServiceServer
// for forward compatibility.
//
// -------------- Сервис по работе с докторов ---------------
type DoctorAdminServiceServer interface {
	GetDoctors(context.Context, *GetDoctorsRequest) (*GetDoctorsResponse, error)
	GetDoctorsByIDs(context.Context, *GetDoctorsByIDsRequest) (*GetDoctorsByIDsResponse, error)
	SortDoctors(context.Context, *SortDoctorsRequest) (*SortDoctorsResponse, error)
	// todo подумать тоже, а надо ли тут эту сортировку
	//
	//	rpc FilterDoctors(FilterDoctorsRequest) returns (FilterDoctorsResponse) {
	//	    option (google.api.http) = {
	//	        post: "/api/v1/admin/doctors/filter"
	//	        body: "*"
	//	    };
	//	    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
	//	        summary: "Фильтрация врачей"
	//	    };
	//	}
	SearchDoctors(context.Context, *SearchDoctorsRequest) (*SearchDoctorsResponse, error)
	GetDoctorByID(context.Context, *GetDoctorByIDRequest) (*GetDoctorByIDResponse, error)
	UpdateDoctor(context.Context, *UpdateDoctorRequest) (*UpdateDoctorResponse, error)
	DeleteDoctor(context.Context, *DeleteDoctorRequest) (*DeleteDoctorResponse, error)
	ActivateDoctor(context.Context, *ActivateDoctorRequest) (*ActivateDoctorResponse, error)
	DeactivateDoctor(context.Context, *DeactivateDoctorRequest) (*DeactivateDoctorResponse, error)
	SaveDoctorPhoto(context.Context, *SaveDoctorPhotoRequest) (*SaveDoctorPhotoResponse, error)
	AddAdditionalCity(context.Context, *AddDoctorAdditionalCityRequest) (*AddDoctorAdditionalCityResponse, error)
	AddAdditionalSpeciality(context.Context, *AddDoctorAdditionalSpecialityRequest) (*AddDoctorAdditionalSpecialityResponse, error)
	DeleteAdditionalCity(context.Context, *DeleteDoctorAdditionalCityRequest) (*DeleteDoctorAdditionalCityResponse, error)
	DeleteAdditionalSpeciality(context.Context, *DeleteDoctorAdditionalSpecialityRequest) (*DeleteDoctorAdditionalSpecialityResponse, error)
	UpdateSubscribers(context.Context, *UpdateSubscribersRequest) (*UpdateSubscribersResponse, error)
}

// UnimplementedDoctorAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorAdminServiceServer struct{}

func (UnimplementedDoctorAdminServiceServer) GetDoctors(context.Context, *GetDoctorsRequest) (*GetDoctorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoctors not implemented")
}
func (UnimplementedDoctorAdminServiceServer) GetDoctorsByIDs(context.Context, *GetDoctorsByIDsRequest) (*GetDoctorsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoctorsByIDs not implemented")
}
func (UnimplementedDoctorAdminServiceServer) SortDoctors(context.Context, *SortDoctorsRequest) (*SortDoctorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SortDoctors not implemented")
}
func (UnimplementedDoctorAdminServiceServer) SearchDoctors(context.Context, *SearchDoctorsRequest) (*SearchDoctorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDoctors not implemented")
}
func (UnimplementedDoctorAdminServiceServer) GetDoctorByID(context.Context, *GetDoctorByIDRequest) (*GetDoctorByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoctorByID not implemented")
}
func (UnimplementedDoctorAdminServiceServer) UpdateDoctor(context.Context, *UpdateDoctorRequest) (*UpdateDoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDoctor not implemented")
}
func (UnimplementedDoctorAdminServiceServer) DeleteDoctor(context.Context, *DeleteDoctorRequest) (*DeleteDoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDoctor not implemented")
}
func (UnimplementedDoctorAdminServiceServer) ActivateDoctor(context.Context, *ActivateDoctorRequest) (*ActivateDoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDoctor not implemented")
}
func (UnimplementedDoctorAdminServiceServer) DeactivateDoctor(context.Context, *DeactivateDoctorRequest) (*DeactivateDoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateDoctor not implemented")
}
func (UnimplementedDoctorAdminServiceServer) SaveDoctorPhoto(context.Context, *SaveDoctorPhotoRequest) (*SaveDoctorPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDoctorPhoto not implemented")
}
func (UnimplementedDoctorAdminServiceServer) AddAdditionalCity(context.Context, *AddDoctorAdditionalCityRequest) (*AddDoctorAdditionalCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdditionalCity not implemented")
}
func (UnimplementedDoctorAdminServiceServer) AddAdditionalSpeciality(context.Context, *AddDoctorAdditionalSpecialityRequest) (*AddDoctorAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdditionalSpeciality not implemented")
}
func (UnimplementedDoctorAdminServiceServer) DeleteAdditionalCity(context.Context, *DeleteDoctorAdditionalCityRequest) (*DeleteDoctorAdditionalCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdditionalCity not implemented")
}
func (UnimplementedDoctorAdminServiceServer) DeleteAdditionalSpeciality(context.Context, *DeleteDoctorAdditionalSpecialityRequest) (*DeleteDoctorAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdditionalSpeciality not implemented")
}
func (UnimplementedDoctorAdminServiceServer) UpdateSubscribers(context.Context, *UpdateSubscribersRequest) (*UpdateSubscribersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubscribers not implemented")
}
func (UnimplementedDoctorAdminServiceServer) testEmbeddedByValue() {}

// UnsafeDoctorAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorAdminServiceServer will
// result in compilation errors.
type UnsafeDoctorAdminServiceServer interface {
	mustEmbedUnimplementedDoctorAdminServiceServer()
}

func RegisterDoctorAdminServiceServer(s grpc.ServiceRegistrar, srv DoctorAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDoctorAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorAdminService_ServiceDesc, srv)
}

func _DoctorAdminService_GetDoctors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).GetDoctors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_GetDoctors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).GetDoctors(ctx, req.(*GetDoctorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_GetDoctorsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).GetDoctorsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_GetDoctorsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).GetDoctorsByIDs(ctx, req.(*GetDoctorsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_SortDoctors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortDoctorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).SortDoctors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_SortDoctors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).SortDoctors(ctx, req.(*SortDoctorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_SearchDoctors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDoctorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).SearchDoctors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_SearchDoctors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).SearchDoctors(ctx, req.(*SearchDoctorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_GetDoctorByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).GetDoctorByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_GetDoctorByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).GetDoctorByID(ctx, req.(*GetDoctorByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_UpdateDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).UpdateDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_UpdateDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).UpdateDoctor(ctx, req.(*UpdateDoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_DeleteDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).DeleteDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_DeleteDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).DeleteDoctor(ctx, req.(*DeleteDoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_ActivateDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).ActivateDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_ActivateDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).ActivateDoctor(ctx, req.(*ActivateDoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_DeactivateDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateDoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).DeactivateDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_DeactivateDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).DeactivateDoctor(ctx, req.(*DeactivateDoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_SaveDoctorPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDoctorPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).SaveDoctorPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_SaveDoctorPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).SaveDoctorPhoto(ctx, req.(*SaveDoctorPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_AddAdditionalCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDoctorAdditionalCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).AddAdditionalCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_AddAdditionalCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).AddAdditionalCity(ctx, req.(*AddDoctorAdditionalCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_AddAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDoctorAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).AddAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_AddAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).AddAdditionalSpeciality(ctx, req.(*AddDoctorAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_DeleteAdditionalCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDoctorAdditionalCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).DeleteAdditionalCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_DeleteAdditionalCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).DeleteAdditionalCity(ctx, req.(*DeleteDoctorAdditionalCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_DeleteAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDoctorAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).DeleteAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_DeleteAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).DeleteAdditionalSpeciality(ctx, req.(*DeleteDoctorAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminService_UpdateSubscribers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscribersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminServiceServer).UpdateSubscribers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminService_UpdateSubscribers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminServiceServer).UpdateSubscribers(ctx, req.(*UpdateSubscribersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorAdminService_ServiceDesc is the grpc.ServiceDesc for DoctorAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoctorAdminService",
	HandlerType: (*DoctorAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDoctors",
			Handler:    _DoctorAdminService_GetDoctors_Handler,
		},
		{
			MethodName: "GetDoctorsByIDs",
			Handler:    _DoctorAdminService_GetDoctorsByIDs_Handler,
		},
		{
			MethodName: "SortDoctors",
			Handler:    _DoctorAdminService_SortDoctors_Handler,
		},
		{
			MethodName: "SearchDoctors",
			Handler:    _DoctorAdminService_SearchDoctors_Handler,
		},
		{
			MethodName: "GetDoctorByID",
			Handler:    _DoctorAdminService_GetDoctorByID_Handler,
		},
		{
			MethodName: "UpdateDoctor",
			Handler:    _DoctorAdminService_UpdateDoctor_Handler,
		},
		{
			MethodName: "DeleteDoctor",
			Handler:    _DoctorAdminService_DeleteDoctor_Handler,
		},
		{
			MethodName: "ActivateDoctor",
			Handler:    _DoctorAdminService_ActivateDoctor_Handler,
		},
		{
			MethodName: "DeactivateDoctor",
			Handler:    _DoctorAdminService_DeactivateDoctor_Handler,
		},
		{
			MethodName: "SaveDoctorPhoto",
			Handler:    _DoctorAdminService_SaveDoctorPhoto_Handler,
		},
		{
			MethodName: "AddAdditionalCity",
			Handler:    _DoctorAdminService_AddAdditionalCity_Handler,
		},
		{
			MethodName: "AddAdditionalSpeciality",
			Handler:    _DoctorAdminService_AddAdditionalSpeciality_Handler,
		},
		{
			MethodName: "DeleteAdditionalCity",
			Handler:    _DoctorAdminService_DeleteAdditionalCity_Handler,
		},
		{
			MethodName: "DeleteAdditionalSpeciality",
			Handler:    _DoctorAdminService_DeleteAdditionalSpeciality_Handler,
		},
		{
			MethodName: "UpdateSubscribers",
			Handler:    _DoctorAdminService_UpdateSubscribers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/doctors/v1/admin.proto",
}

const (
	DoctorAdminCityService_GetCities_FullMethodName    = "/DoctorAdminCityService/GetCities"
	DoctorAdminCityService_SearchCities_FullMethodName = "/DoctorAdminCityService/SearchCities"
	DoctorAdminCityService_CreateCity_FullMethodName   = "/DoctorAdminCityService/CreateCity"
	DoctorAdminCityService_DeleteCity_FullMethodName   = "/DoctorAdminCityService/DeleteCity"
)

// DoctorAdminCityServiceClient is the client API for DoctorAdminCityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------- Сервис по работе с городами докторов ---------------
type DoctorAdminCityServiceClient interface {
	GetCities(ctx context.Context, in *GetDoctorsCitiesRequest, opts ...grpc.CallOption) (*GetDoctorsCitiesResponse, error)
	SearchCities(ctx context.Context, in *SearchDoctorsCitiesRequest, opts ...grpc.CallOption) (*SearchDoctorsCitiesResponse, error)
	CreateCity(ctx context.Context, in *CreateDoctorsCityRequest, opts ...grpc.CallOption) (*CreateDoctorsCityResponse, error)
	DeleteCity(ctx context.Context, in *DeleteDoctorsCityRequest, opts ...grpc.CallOption) (*DeleteDoctorsCityResponse, error)
}

type doctorAdminCityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorAdminCityServiceClient(cc grpc.ClientConnInterface) DoctorAdminCityServiceClient {
	return &doctorAdminCityServiceClient{cc}
}

func (c *doctorAdminCityServiceClient) GetCities(ctx context.Context, in *GetDoctorsCitiesRequest, opts ...grpc.CallOption) (*GetDoctorsCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsCitiesResponse)
	err := c.cc.Invoke(ctx, DoctorAdminCityService_GetCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminCityServiceClient) SearchCities(ctx context.Context, in *SearchDoctorsCitiesRequest, opts ...grpc.CallOption) (*SearchDoctorsCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDoctorsCitiesResponse)
	err := c.cc.Invoke(ctx, DoctorAdminCityService_SearchCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminCityServiceClient) CreateCity(ctx context.Context, in *CreateDoctorsCityRequest, opts ...grpc.CallOption) (*CreateDoctorsCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDoctorsCityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminCityService_CreateCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminCityServiceClient) DeleteCity(ctx context.Context, in *DeleteDoctorsCityRequest, opts ...grpc.CallOption) (*DeleteDoctorsCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDoctorsCityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminCityService_DeleteCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorAdminCityServiceServer is the server API for DoctorAdminCityService service.
// All implementations should embed UnimplementedDoctorAdminCityServiceServer
// for forward compatibility.
//
// -------------- Сервис по работе с городами докторов ---------------
type DoctorAdminCityServiceServer interface {
	GetCities(context.Context, *GetDoctorsCitiesRequest) (*GetDoctorsCitiesResponse, error)
	SearchCities(context.Context, *SearchDoctorsCitiesRequest) (*SearchDoctorsCitiesResponse, error)
	CreateCity(context.Context, *CreateDoctorsCityRequest) (*CreateDoctorsCityResponse, error)
	DeleteCity(context.Context, *DeleteDoctorsCityRequest) (*DeleteDoctorsCityResponse, error)
}

// UnimplementedDoctorAdminCityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorAdminCityServiceServer struct{}

func (UnimplementedDoctorAdminCityServiceServer) GetCities(context.Context, *GetDoctorsCitiesRequest) (*GetDoctorsCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCities not implemented")
}
func (UnimplementedDoctorAdminCityServiceServer) SearchCities(context.Context, *SearchDoctorsCitiesRequest) (*SearchDoctorsCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCities not implemented")
}
func (UnimplementedDoctorAdminCityServiceServer) CreateCity(context.Context, *CreateDoctorsCityRequest) (*CreateDoctorsCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCity not implemented")
}
func (UnimplementedDoctorAdminCityServiceServer) DeleteCity(context.Context, *DeleteDoctorsCityRequest) (*DeleteDoctorsCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCity not implemented")
}
func (UnimplementedDoctorAdminCityServiceServer) testEmbeddedByValue() {}

// UnsafeDoctorAdminCityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorAdminCityServiceServer will
// result in compilation errors.
type UnsafeDoctorAdminCityServiceServer interface {
	mustEmbedUnimplementedDoctorAdminCityServiceServer()
}

func RegisterDoctorAdminCityServiceServer(s grpc.ServiceRegistrar, srv DoctorAdminCityServiceServer) {
	// If the following call panics, it indicates UnimplementedDoctorAdminCityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorAdminCityService_ServiceDesc, srv)
}

func _DoctorAdminCityService_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminCityServiceServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminCityService_GetCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminCityServiceServer).GetCities(ctx, req.(*GetDoctorsCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminCityService_SearchCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDoctorsCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminCityServiceServer).SearchCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminCityService_SearchCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminCityServiceServer).SearchCities(ctx, req.(*SearchDoctorsCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminCityService_CreateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDoctorsCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminCityServiceServer).CreateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminCityService_CreateCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminCityServiceServer).CreateCity(ctx, req.(*CreateDoctorsCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminCityService_DeleteCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDoctorsCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminCityServiceServer).DeleteCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminCityService_DeleteCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminCityServiceServer).DeleteCity(ctx, req.(*DeleteDoctorsCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorAdminCityService_ServiceDesc is the grpc.ServiceDesc for DoctorAdminCityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorAdminCityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoctorAdminCityService",
	HandlerType: (*DoctorAdminCityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCities",
			Handler:    _DoctorAdminCityService_GetCities_Handler,
		},
		{
			MethodName: "SearchCities",
			Handler:    _DoctorAdminCityService_SearchCities_Handler,
		},
		{
			MethodName: "CreateCity",
			Handler:    _DoctorAdminCityService_CreateCity_Handler,
		},
		{
			MethodName: "DeleteCity",
			Handler:    _DoctorAdminCityService_DeleteCity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/doctors/v1/admin.proto",
}

const (
	DoctorAdminSpecialityService_GetSpecialities_FullMethodName            = "/DoctorAdminSpecialityService/GetSpecialities"
	DoctorAdminSpecialityService_SearchSpeciality_FullMethodName           = "/DoctorAdminSpecialityService/SearchSpeciality"
	DoctorAdminSpecialityService_CreateSpeciality_FullMethodName           = "/DoctorAdminSpecialityService/CreateSpeciality"
	DoctorAdminSpecialityService_GetSpeciality_FullMethodName              = "/DoctorAdminSpecialityService/GetSpeciality"
	DoctorAdminSpecialityService_AddAdditionalSpeciality_FullMethodName    = "/DoctorAdminSpecialityService/AddAdditionalSpeciality"
	DoctorAdminSpecialityService_DeleteAdditionalSpeciality_FullMethodName = "/DoctorAdminSpecialityService/DeleteAdditionalSpeciality"
)

// DoctorAdminSpecialityServiceClient is the client API for DoctorAdminSpecialityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------- Сервис по работе со специальностями докторов ---------------
type DoctorAdminSpecialityServiceClient interface {
	GetSpecialities(ctx context.Context, in *GetDoctorsSpecialitiesRequest, opts ...grpc.CallOption) (*GetDoctorsSpecialitiesResponse, error)
	SearchSpeciality(ctx context.Context, in *SearchDoctorsSpecialityRequest, opts ...grpc.CallOption) (*SearchDoctorsSpecialityResponse, error)
	CreateSpeciality(ctx context.Context, in *CreateDoctorsSpecialityRequest, opts ...grpc.CallOption) (*CreateDoctorsSpecialityResponse, error)
	GetSpeciality(ctx context.Context, in *GetSpecialityRequest, opts ...grpc.CallOption) (*GetSpecialityResponse, error)
	AddAdditionalSpeciality(ctx context.Context, in *AddAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddAdditionalSpecialityResponse, error)
	DeleteAdditionalSpeciality(ctx context.Context, in *DeleteAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteAdditionalSpecialityResponse, error)
}

type doctorAdminSpecialityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorAdminSpecialityServiceClient(cc grpc.ClientConnInterface) DoctorAdminSpecialityServiceClient {
	return &doctorAdminSpecialityServiceClient{cc}
}

func (c *doctorAdminSpecialityServiceClient) GetSpecialities(ctx context.Context, in *GetDoctorsSpecialitiesRequest, opts ...grpc.CallOption) (*GetDoctorsSpecialitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsSpecialitiesResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_GetSpecialities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminSpecialityServiceClient) SearchSpeciality(ctx context.Context, in *SearchDoctorsSpecialityRequest, opts ...grpc.CallOption) (*SearchDoctorsSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDoctorsSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_SearchSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminSpecialityServiceClient) CreateSpeciality(ctx context.Context, in *CreateDoctorsSpecialityRequest, opts ...grpc.CallOption) (*CreateDoctorsSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDoctorsSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_CreateSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminSpecialityServiceClient) GetSpeciality(ctx context.Context, in *GetSpecialityRequest, opts ...grpc.CallOption) (*GetSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_GetSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminSpecialityServiceClient) AddAdditionalSpeciality(ctx context.Context, in *AddAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_AddAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorAdminSpecialityServiceClient) DeleteAdditionalSpeciality(ctx context.Context, in *DeleteAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, DoctorAdminSpecialityService_DeleteAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorAdminSpecialityServiceServer is the server API for DoctorAdminSpecialityService service.
// All implementations should embed UnimplementedDoctorAdminSpecialityServiceServer
// for forward compatibility.
//
// -------------- Сервис по работе со специальностями докторов ---------------
type DoctorAdminSpecialityServiceServer interface {
	GetSpecialities(context.Context, *GetDoctorsSpecialitiesRequest) (*GetDoctorsSpecialitiesResponse, error)
	SearchSpeciality(context.Context, *SearchDoctorsSpecialityRequest) (*SearchDoctorsSpecialityResponse, error)
	CreateSpeciality(context.Context, *CreateDoctorsSpecialityRequest) (*CreateDoctorsSpecialityResponse, error)
	GetSpeciality(context.Context, *GetSpecialityRequest) (*GetSpecialityResponse, error)
	AddAdditionalSpeciality(context.Context, *AddAdditionalSpecialityRequest) (*AddAdditionalSpecialityResponse, error)
	DeleteAdditionalSpeciality(context.Context, *DeleteAdditionalSpecialityRequest) (*DeleteAdditionalSpecialityResponse, error)
}

// UnimplementedDoctorAdminSpecialityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorAdminSpecialityServiceServer struct{}

func (UnimplementedDoctorAdminSpecialityServiceServer) GetSpecialities(context.Context, *GetDoctorsSpecialitiesRequest) (*GetDoctorsSpecialitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpecialities not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) SearchSpeciality(context.Context, *SearchDoctorsSpecialityRequest) (*SearchDoctorsSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSpeciality not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) CreateSpeciality(context.Context, *CreateDoctorsSpecialityRequest) (*CreateDoctorsSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpeciality not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) GetSpeciality(context.Context, *GetSpecialityRequest) (*GetSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpeciality not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) AddAdditionalSpeciality(context.Context, *AddAdditionalSpecialityRequest) (*AddAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdditionalSpeciality not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) DeleteAdditionalSpeciality(context.Context, *DeleteAdditionalSpecialityRequest) (*DeleteAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdditionalSpeciality not implemented")
}
func (UnimplementedDoctorAdminSpecialityServiceServer) testEmbeddedByValue() {}

// UnsafeDoctorAdminSpecialityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorAdminSpecialityServiceServer will
// result in compilation errors.
type UnsafeDoctorAdminSpecialityServiceServer interface {
	mustEmbedUnimplementedDoctorAdminSpecialityServiceServer()
}

func RegisterDoctorAdminSpecialityServiceServer(s grpc.ServiceRegistrar, srv DoctorAdminSpecialityServiceServer) {
	// If the following call panics, it indicates UnimplementedDoctorAdminSpecialityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorAdminSpecialityService_ServiceDesc, srv)
}

func _DoctorAdminSpecialityService_GetSpecialities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsSpecialitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).GetSpecialities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_GetSpecialities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).GetSpecialities(ctx, req.(*GetDoctorsSpecialitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminSpecialityService_SearchSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDoctorsSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).SearchSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_SearchSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).SearchSpeciality(ctx, req.(*SearchDoctorsSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminSpecialityService_CreateSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDoctorsSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).CreateSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_CreateSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).CreateSpeciality(ctx, req.(*CreateDoctorsSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminSpecialityService_GetSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).GetSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_GetSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).GetSpeciality(ctx, req.(*GetSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminSpecialityService_AddAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).AddAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_AddAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).AddAdditionalSpeciality(ctx, req.(*AddAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorAdminSpecialityService_DeleteAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorAdminSpecialityServiceServer).DeleteAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorAdminSpecialityService_DeleteAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorAdminSpecialityServiceServer).DeleteAdditionalSpeciality(ctx, req.(*DeleteAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorAdminSpecialityService_ServiceDesc is the grpc.ServiceDesc for DoctorAdminSpecialityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorAdminSpecialityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoctorAdminSpecialityService",
	HandlerType: (*DoctorAdminSpecialityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpecialities",
			Handler:    _DoctorAdminSpecialityService_GetSpecialities_Handler,
		},
		{
			MethodName: "SearchSpeciality",
			Handler:    _DoctorAdminSpecialityService_SearchSpeciality_Handler,
		},
		{
			MethodName: "CreateSpeciality",
			Handler:    _DoctorAdminSpecialityService_CreateSpeciality_Handler,
		},
		{
			MethodName: "GetSpeciality",
			Handler:    _DoctorAdminSpecialityService_GetSpeciality_Handler,
		},
		{
			MethodName: "AddAdditionalSpeciality",
			Handler:    _DoctorAdminSpecialityService_AddAdditionalSpeciality_Handler,
		},
		{
			MethodName: "DeleteAdditionalSpeciality",
			Handler:    _DoctorAdminSpecialityService_DeleteAdditionalSpeciality_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/doctors/v1/admin.proto",
}
