// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/mm/v1/admin.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MmDatetime    string                 `protobuf:"bytes,1,opt,name=mm_datetime,json=mmDatetime,proto3" json:"mm_datetime,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MmLink        string                 `protobuf:"bytes,3,opt,name=mm_link,json=mmLink,proto3" json:"mm_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMMRequest) Reset() {
	*x = CreateMMRequest{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMMRequest) ProtoMessage() {}

func (x *CreateMMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMMRequest.ProtoReflect.Descriptor instead.
func (*CreateMMRequest) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMMRequest) GetMmDatetime() string {
	if x != nil {
		return x.MmDatetime
	}
	return ""
}

func (x *CreateMMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMMRequest) GetMmLink() string {
	if x != nil {
		return x.MmLink
	}
	return ""
}

type CreateMMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMMResponse) Reset() {
	*x = CreateMMResponse{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMMResponse) ProtoMessage() {}

func (x *CreateMMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMMResponse.ProtoReflect.Descriptor instead.
func (*CreateMMResponse) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ManualNotificationMMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MmId          int64                  `protobuf:"varint,1,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualNotificationMMRequest) Reset() {
	*x = ManualNotificationMMRequest{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualNotificationMMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualNotificationMMRequest) ProtoMessage() {}

func (x *ManualNotificationMMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualNotificationMMRequest.ProtoReflect.Descriptor instead.
func (*ManualNotificationMMRequest) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ManualNotificationMMRequest) GetMmId() int64 {
	if x != nil {
		return x.MmId
	}
	return 0
}

type ManualNotificationMMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualNotificationMMResponse) Reset() {
	*x = ManualNotificationMMResponse{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualNotificationMMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualNotificationMMResponse) ProtoMessage() {}

func (x *ManualNotificationMMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualNotificationMMResponse.ProtoReflect.Descriptor instead.
func (*ManualNotificationMMResponse) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{3}
}

type ChangeMMActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MmId          int64                  `protobuf:"varint,1,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	Activity      bool                   `protobuf:"varint,2,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMMActivityRequest) Reset() {
	*x = ChangeMMActivityRequest{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMMActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMMActivityRequest) ProtoMessage() {}

func (x *ChangeMMActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMMActivityRequest.ProtoReflect.Descriptor instead.
func (*ChangeMMActivityRequest) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeMMActivityRequest) GetMmId() int64 {
	if x != nil {
		return x.MmId
	}
	return 0
}

func (x *ChangeMMActivityRequest) GetActivity() bool {
	if x != nil {
		return x.Activity
	}
	return false
}

type ChangeMMActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMMActivityResponse) Reset() {
	*x = ChangeMMActivityResponse{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMMActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMMActivityResponse) ProtoMessage() {}

func (x *ChangeMMActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMMActivityResponse.ProtoReflect.Descriptor instead.
func (*ChangeMMActivityResponse) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{5}
}

type GetMMListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMMListRequest) Reset() {
	*x = GetMMListRequest{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMMListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMMListRequest) ProtoMessage() {}

func (x *GetMMListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMMListRequest.ProtoReflect.Descriptor instead.
func (*GetMMListRequest) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{6}
}

type GetMMListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Mms           []*GetMMListResponse_Mm `protobuf:"bytes,1,rep,name=mms,proto3" json:"mms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMMListResponse) Reset() {
	*x = GetMMListResponse{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMMListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMMListResponse) ProtoMessage() {}

func (x *GetMMListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMMListResponse.ProtoReflect.Descriptor instead.
func (*GetMMListResponse) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetMMListResponse) GetMms() []*GetMMListResponse_Mm {
	if x != nil {
		return x.Mms
	}
	return nil
}

type CreateGetCourseOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	GetcourceId   int64                  `protobuf:"varint,2,opt,name=getcource_id,json=getcourceId,proto3" json:"getcource_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGetCourseOrderRequest) Reset() {
	*x = CreateGetCourseOrderRequest{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGetCourseOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGetCourseOrderRequest) ProtoMessage() {}

func (x *CreateGetCourseOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGetCourseOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateGetCourseOrderRequest) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGetCourseOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateGetCourseOrderRequest) GetGetcourceId() int64 {
	if x != nil {
		return x.GetcourceId
	}
	return 0
}

func (x *CreateGetCourseOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGetCourseOrderRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type CreateGetCourseOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGetCourseOrderResponse) Reset() {
	*x = CreateGetCourseOrderResponse{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGetCourseOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGetCourseOrderResponse) ProtoMessage() {}

func (x *CreateGetCourseOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGetCourseOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateGetCourseOrderResponse) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{9}
}

type GetMMListResponse_Mm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MmId          int64                  `protobuf:"varint,1,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	MmDatetime    string                 `protobuf:"bytes,2,opt,name=mm_datetime,json=mmDatetime,proto3" json:"mm_datetime,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Activity      bool                   `protobuf:"varint,6,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMMListResponse_Mm) Reset() {
	*x = GetMMListResponse_Mm{}
	mi := &file_admin_mm_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMMListResponse_Mm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMMListResponse_Mm) ProtoMessage() {}

func (x *GetMMListResponse_Mm) ProtoReflect() protoreflect.Message {
	mi := &file_admin_mm_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMMListResponse_Mm.ProtoReflect.Descriptor instead.
func (*GetMMListResponse_Mm) Descriptor() ([]byte, []int) {
	return file_admin_mm_v1_admin_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetMMListResponse_Mm) GetMmId() int64 {
	if x != nil {
		return x.MmId
	}
	return 0
}

func (x *GetMMListResponse_Mm) GetMmDatetime() string {
	if x != nil {
		return x.MmDatetime
	}
	return ""
}

func (x *GetMMListResponse_Mm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMMListResponse_Mm) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetMMListResponse_Mm) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMMListResponse_Mm) GetActivity() bool {
	if x != nil {
		return x.Activity
	}
	return false
}

var File_admin_mm_v1_admin_proto protoreflect.FileDescriptor

const file_admin_mm_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x17admin/mm/v1/admin.proto\x12\vadmin.mm.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"_\n" +
	"\x0fCreateMMRequest\x12\x1f\n" +
	"\vmm_datetime\x18\x01 \x01(\tR\n" +
	"mmDatetime\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\amm_link\x18\x03 \x01(\tR\x06mmLink\"\x12\n" +
	"\x10CreateMMResponse\"2\n" +
	"\x1bManualNotificationMMRequest\x12\x13\n" +
	"\x05mm_id\x18\x01 \x01(\x03R\x04mmId\"\x1e\n" +
	"\x1cManualNotificationMMResponse\"J\n" +
	"\x17ChangeMMActivityRequest\x12\x13\n" +
	"\x05mm_id\x18\x01 \x01(\x03R\x04mmId\x12\x1a\n" +
	"\bactivity\x18\x02 \x01(\bR\bactivity\"\x1a\n" +
	"\x18ChangeMMActivityResponse\"\x12\n" +
	"\x10GetMMListRequest\"\xec\x01\n" +
	"\x11GetMMListResponse\x123\n" +
	"\x03mms\x18\x01 \x03(\v2!.admin.mm.v1.GetMMListResponse.MmR\x03mms\x1a\xa1\x01\n" +
	"\x02Mm\x12\x13\n" +
	"\x05mm_id\x18\x01 \x01(\x03R\x04mmId\x12\x1f\n" +
	"\vmm_datetime\x18\x02 \x01(\tR\n" +
	"mmDatetime\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bactivity\x18\x06 \x01(\bR\bactivity\"\x8b\x01\n" +
	"\x1bCreateGetCourseOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fgetcource_id\x18\x02 \x01(\x03R\vgetcourceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\"\x1e\n" +
	"\x1cCreateGetCourseOrderResponse2\xfc\a\n" +
	"\x0eMMAdminService\x12\x92\x01\n" +
	"\bCreateMM\x12\x1c.admin.mm.v1.CreateMMRequest\x1a\x1d.admin.mm.v1.CreateMMResponse\"I\x92A+\x12)Создание мастермайнда\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/admin/mm\x12\xcb\x01\n" +
	"\x14ManualNotificationMM\x12(.admin.mm.v1.ManualNotificationMMRequest\x1a).admin.mm.v1.ManualNotificationMMResponse\"^\x92A$\x12\"Ручная рассылка ММ\x82\xd3\xe4\x93\x021:\x01*\",/api/v1/admin/mm/{mm_id}/manual_notification\x12\xda\x01\n" +
	"\x10ChangeMMActivity\x12$.admin.mm.v1.ChangeMMActivityRequest\x1a%.admin.mm.v1.ChangeMMActivityResponse\"y\x92A@\x12>Изменение активности ММ (вкл/выкл)\x82\xd3\xe4\x93\x020:\x01*\"+/api/v1/admin/mm/{mm_id}/change_mm_activity\x12\xa3\x01\n" +
	"\tGetMMList\x12\x1d.admin.mm.v1.GetMMListRequest\x1a\x1e.admin.mm.v1.GetMMListResponse\"W\x92A<\x12:Получение списка мастермайндов\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/admin/mm\x12\x83\x02\n" +
	"\x14CreateGetCourseOrder\x12(.admin.mm.v1.CreateGetCourseOrderRequest\x1a).admin.mm.v1.CreateGetCourseOrderResponse\"\x95\x01\x92Aj\x123Создание заказа от геткурса2!application/x-www-form-urlencoded:\x10application/json\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/admin/gk_order/createB\x11Z\x0fapi/admin/mm/v1b\x06proto3"

var (
	file_admin_mm_v1_admin_proto_rawDescOnce sync.Once
	file_admin_mm_v1_admin_proto_rawDescData []byte
)

func file_admin_mm_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_mm_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_mm_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_mm_v1_admin_proto_rawDesc), len(file_admin_mm_v1_admin_proto_rawDesc)))
	})
	return file_admin_mm_v1_admin_proto_rawDescData
}

var file_admin_mm_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_admin_mm_v1_admin_proto_goTypes = []any{
	(*CreateMMRequest)(nil),              // 0: admin.mm.v1.CreateMMRequest
	(*CreateMMResponse)(nil),             // 1: admin.mm.v1.CreateMMResponse
	(*ManualNotificationMMRequest)(nil),  // 2: admin.mm.v1.ManualNotificationMMRequest
	(*ManualNotificationMMResponse)(nil), // 3: admin.mm.v1.ManualNotificationMMResponse
	(*ChangeMMActivityRequest)(nil),      // 4: admin.mm.v1.ChangeMMActivityRequest
	(*ChangeMMActivityResponse)(nil),     // 5: admin.mm.v1.ChangeMMActivityResponse
	(*GetMMListRequest)(nil),             // 6: admin.mm.v1.GetMMListRequest
	(*GetMMListResponse)(nil),            // 7: admin.mm.v1.GetMMListResponse
	(*CreateGetCourseOrderRequest)(nil),  // 8: admin.mm.v1.CreateGetCourseOrderRequest
	(*CreateGetCourseOrderResponse)(nil), // 9: admin.mm.v1.CreateGetCourseOrderResponse
	(*GetMMListResponse_Mm)(nil),         // 10: admin.mm.v1.GetMMListResponse.Mm
}
var file_admin_mm_v1_admin_proto_depIdxs = []int32{
	10, // 0: admin.mm.v1.GetMMListResponse.mms:type_name -> admin.mm.v1.GetMMListResponse.Mm
	0,  // 1: admin.mm.v1.MMAdminService.CreateMM:input_type -> admin.mm.v1.CreateMMRequest
	2,  // 2: admin.mm.v1.MMAdminService.ManualNotificationMM:input_type -> admin.mm.v1.ManualNotificationMMRequest
	4,  // 3: admin.mm.v1.MMAdminService.ChangeMMActivity:input_type -> admin.mm.v1.ChangeMMActivityRequest
	6,  // 4: admin.mm.v1.MMAdminService.GetMMList:input_type -> admin.mm.v1.GetMMListRequest
	8,  // 5: admin.mm.v1.MMAdminService.CreateGetCourseOrder:input_type -> admin.mm.v1.CreateGetCourseOrderRequest
	1,  // 6: admin.mm.v1.MMAdminService.CreateMM:output_type -> admin.mm.v1.CreateMMResponse
	3,  // 7: admin.mm.v1.MMAdminService.ManualNotificationMM:output_type -> admin.mm.v1.ManualNotificationMMResponse
	5,  // 8: admin.mm.v1.MMAdminService.ChangeMMActivity:output_type -> admin.mm.v1.ChangeMMActivityResponse
	7,  // 9: admin.mm.v1.MMAdminService.GetMMList:output_type -> admin.mm.v1.GetMMListResponse
	9,  // 10: admin.mm.v1.MMAdminService.CreateGetCourseOrder:output_type -> admin.mm.v1.CreateGetCourseOrderResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_admin_mm_v1_admin_proto_init() }
func file_admin_mm_v1_admin_proto_init() {
	if File_admin_mm_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_mm_v1_admin_proto_rawDesc), len(file_admin_mm_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_mm_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_mm_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_mm_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_mm_v1_admin_proto = out.File
	file_admin_mm_v1_admin_proto_goTypes = nil
	file_admin_mm_v1_admin_proto_depIdxs = nil
}
