// Code generated by protoc-gen-goclay. DO NOT EDIT.

package v1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src admin_grpc.pb.go --interface-name MMAdminServiceServer --mod-relative --dst

//go:embed admin.swagger.json
var Swagger []byte

// MMAdminServiceServiceDesc is a descriptor/registrator for the MMAdminServiceServer.
type MMAdminServiceServiceDesc struct {
	svc  MMAdminServiceServer
	opts httptransport.DescOptions
}

// NewMMAdminServiceServiceDesc creates new registrator for the MMAdminServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewMMAdminServiceServiceDesc(i MMAdminServiceServer) *MMAdminServiceServiceDesc {
	return &MMAdminServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *MMAdminServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterMMAdminServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *MMAdminServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *MMAdminServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *MMAdminServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterMMAdminServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *MMAdminServiceServiceDesc) CreateMM(ctx context.Context, in *CreateMMRequest) (*CreateMMResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateMM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/admin.mm.v1.MMAdminService/CreateMM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateMM(ctx, req.(*CreateMMRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateMMResponse), err
}

func (w *MMAdminServiceServiceDesc) ManualNotificationMM(ctx context.Context, in *ManualNotificationMMRequest) (*ManualNotificationMMResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.ManualNotificationMM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/admin.mm.v1.MMAdminService/ManualNotificationMM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.ManualNotificationMM(ctx, req.(*ManualNotificationMMRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*ManualNotificationMMResponse), err
}

func (w *MMAdminServiceServiceDesc) ChangeMMActivity(ctx context.Context, in *ChangeMMActivityRequest) (*ChangeMMActivityResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.ChangeMMActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/admin.mm.v1.MMAdminService/ChangeMMActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.ChangeMMActivity(ctx, req.(*ChangeMMActivityRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*ChangeMMActivityResponse), err
}

func (w *MMAdminServiceServiceDesc) GetMMList(ctx context.Context, in *GetMMListRequest) (*GetMMListResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetMMList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/admin.mm.v1.MMAdminService/GetMMList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetMMList(ctx, req.(*GetMMListRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetMMListResponse), err
}

func (w *MMAdminServiceServiceDesc) CreateGetCourseOrder(ctx context.Context, in *CreateGetCourseOrderRequest) (*CreateGetCourseOrderResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateGetCourseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/admin.mm.v1.MMAdminService/CreateGetCourseOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateGetCourseOrder(ctx, req.(*CreateGetCourseOrderRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateGetCourseOrderResponse), err
}
