// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: admin/freelancers/freelancer/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FreelancerAdminService_GetFreelancers_FullMethodName                      = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancers"
	FreelancerAdminService_SortFreelancers_FullMethodName                     = "/admin.freelancers.freelancer.v1.FreelancerAdminService/SortFreelancers"
	FreelancerAdminService_SearchFreelancers_FullMethodName                   = "/admin.freelancers.freelancer.v1.FreelancerAdminService/SearchFreelancers"
	FreelancerAdminService_GetFreelancerByID_FullMethodName                   = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerByID"
	FreelancerAdminService_UpdateFreelancer_FullMethodName                    = "/admin.freelancers.freelancer.v1.FreelancerAdminService/UpdateFreelancer"
	FreelancerAdminService_DeleteFreelancer_FullMethodName                    = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeleteFreelancer"
	FreelancerAdminService_ActivateFreelancer_FullMethodName                  = "/admin.freelancers.freelancer.v1.FreelancerAdminService/ActivateFreelancer"
	FreelancerAdminService_DeactivateFreelancer_FullMethodName                = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeactivateFreelancer"
	FreelancerAdminService_SaveFreelancerPhoto_FullMethodName                 = "/admin.freelancers.freelancer.v1.FreelancerAdminService/SaveFreelancerPhoto"
	FreelancerAdminService_AddAdditionalCity_FullMethodName                   = "/admin.freelancers.freelancer.v1.FreelancerAdminService/AddAdditionalCity"
	FreelancerAdminService_AddAdditionalSpeciality_FullMethodName             = "/admin.freelancers.freelancer.v1.FreelancerAdminService/AddAdditionalSpeciality"
	FreelancerAdminService_DeleteAdditionalCity_FullMethodName                = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeleteAdditionalCity"
	FreelancerAdminService_DeleteAdditionalSpeciality_FullMethodName          = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeleteAdditionalSpeciality"
	FreelancerAdminService_AddRecommendation_FullMethodName                   = "/admin.freelancers.freelancer.v1.FreelancerAdminService/AddRecommendation"
	FreelancerAdminService_DeleteRecommendation_FullMethodName                = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeleteRecommendation"
	FreelancerAdminService_ChangeRecommendationSort_FullMethodName            = "/admin.freelancers.freelancer.v1.FreelancerAdminService/ChangeRecommendationSort"
	FreelancerAdminService_AddPriceList_FullMethodName                        = "/admin.freelancers.freelancer.v1.FreelancerAdminService/AddPriceList"
	FreelancerAdminService_DeletePriceList_FullMethodName                     = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeletePriceList"
	FreelancerAdminService_AddNetwork_FullMethodName                          = "/admin.freelancers.freelancer.v1.FreelancerAdminService/AddNetwork"
	FreelancerAdminService_DeleteNetwork_FullMethodName                       = "/admin.freelancers.freelancer.v1.FreelancerAdminService/DeleteNetwork"
	FreelancerAdminService_GetFreelancerAdditionalSpecialities_FullMethodName = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerAdditionalSpecialities"
	FreelancerAdminService_GetFreelancerAdditionalCities_FullMethodName       = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerAdditionalCities"
	FreelancerAdminService_GetFreelancerCooperationTypes_FullMethodName       = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerCooperationTypes"
	FreelancerAdminService_GetFreelancerPriceList_FullMethodName              = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerPriceList"
	FreelancerAdminService_GetFreelancerRecommendations_FullMethodName        = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerRecommendations"
	FreelancerAdminService_GetFreelancerSocialNetworks_FullMethodName         = "/admin.freelancers.freelancer.v1.FreelancerAdminService/GetFreelancerSocialNetworks"
)

// FreelancerAdminServiceClient is the client API for FreelancerAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------- Сервис по работе с докторов ---------------
type FreelancerAdminServiceClient interface {
	GetFreelancers(ctx context.Context, in *GetFreelancersRequest, opts ...grpc.CallOption) (*GetFreelancersResponse, error)
	SortFreelancers(ctx context.Context, in *SortFreelancersRequest, opts ...grpc.CallOption) (*SortFreelancersResponse, error)
	SearchFreelancers(ctx context.Context, in *SearchFreelancersRequest, opts ...grpc.CallOption) (*SearchFreelancersResponse, error)
	GetFreelancerByID(ctx context.Context, in *GetFreelancerByIDRequest, opts ...grpc.CallOption) (*GetFreelancerByIDResponse, error)
	UpdateFreelancer(ctx context.Context, in *UpdateFreelancerRequest, opts ...grpc.CallOption) (*UpdateFreelancerResponse, error)
	DeleteFreelancer(ctx context.Context, in *DeleteFreelancerRequest, opts ...grpc.CallOption) (*DeleteFreelancerResponse, error)
	ActivateFreelancer(ctx context.Context, in *ActivateFreelancerRequest, opts ...grpc.CallOption) (*ActivateFreelancerResponse, error)
	DeactivateFreelancer(ctx context.Context, in *DeactivateFreelancerRequest, opts ...grpc.CallOption) (*DeactivateFreelancerResponse, error)
	SaveFreelancerPhoto(ctx context.Context, in *SaveFreelancerPhotoRequest, opts ...grpc.CallOption) (*SaveFreelancerPhotoResponse, error)
	AddAdditionalCity(ctx context.Context, in *AddAdditionalCityRequest, opts ...grpc.CallOption) (*AddAdditionalCityResponse, error)
	AddAdditionalSpeciality(ctx context.Context, in *AddFreelancerAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddFreelancerAdditionalSpecialityResponse, error)
	DeleteAdditionalCity(ctx context.Context, in *DeleteFreelancerAdditionalCityRequest, opts ...grpc.CallOption) (*DeleteFreelancerAdditionalCityResponse, error)
	DeleteAdditionalSpeciality(ctx context.Context, in *DeleteFreelancerAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteFreelancerAdditionalSpecialityResponse, error)
	AddRecommendation(ctx context.Context, in *AddRecommendationRequest, opts ...grpc.CallOption) (*AddRecommendationResponse, error)
	DeleteRecommendation(ctx context.Context, in *DeleteRecommendationRequest, opts ...grpc.CallOption) (*DeleteRecommendationResponse, error)
	ChangeRecommendationSort(ctx context.Context, in *ChangeRecommendationSortRequest, opts ...grpc.CallOption) (*ChangeRecommendationSortResponse, error)
	AddPriceList(ctx context.Context, in *AddPriceListRequest, opts ...grpc.CallOption) (*AddPriceListResponse, error)
	DeletePriceList(ctx context.Context, in *DeletePriceListRequest, opts ...grpc.CallOption) (*DeletePriceListResponse, error)
	AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	GetFreelancerAdditionalSpecialities(ctx context.Context, in *GetFreelancerAdditionalSpecialitiesRequest, opts ...grpc.CallOption) (*GetFreelancerAdditionalSpecialitiesResponse, error)
	GetFreelancerAdditionalCities(ctx context.Context, in *GetFreelancerAdditionalCitiesRequest, opts ...grpc.CallOption) (*GetFreelancerAdditionalCitiesResponse, error)
	GetFreelancerCooperationTypes(ctx context.Context, in *GetFreelancerCooperationTypesRequest, opts ...grpc.CallOption) (*GetFreelancerCooperationTypesResponse, error)
	GetFreelancerPriceList(ctx context.Context, in *GetFreelancerPriceListRequest, opts ...grpc.CallOption) (*GetFreelancerPriceListResponse, error)
	GetFreelancerRecommendations(ctx context.Context, in *GetFreelancerRecommendationsRequest, opts ...grpc.CallOption) (*GetFreelancerRecommendationsResponse, error)
	GetFreelancerSocialNetworks(ctx context.Context, in *GetFreelancerSocialNetworksRequest, opts ...grpc.CallOption) (*GetFreelancerSocialNetworksResponse, error)
}

type freelancerAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFreelancerAdminServiceClient(cc grpc.ClientConnInterface) FreelancerAdminServiceClient {
	return &freelancerAdminServiceClient{cc}
}

func (c *freelancerAdminServiceClient) GetFreelancers(ctx context.Context, in *GetFreelancersRequest, opts ...grpc.CallOption) (*GetFreelancersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancersResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) SortFreelancers(ctx context.Context, in *SortFreelancersRequest, opts ...grpc.CallOption) (*SortFreelancersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortFreelancersResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_SortFreelancers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) SearchFreelancers(ctx context.Context, in *SearchFreelancersRequest, opts ...grpc.CallOption) (*SearchFreelancersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFreelancersResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_SearchFreelancers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerByID(ctx context.Context, in *GetFreelancerByIDRequest, opts ...grpc.CallOption) (*GetFreelancerByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerByIDResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) UpdateFreelancer(ctx context.Context, in *UpdateFreelancerRequest, opts ...grpc.CallOption) (*UpdateFreelancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFreelancerResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_UpdateFreelancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeleteFreelancer(ctx context.Context, in *DeleteFreelancerRequest, opts ...grpc.CallOption) (*DeleteFreelancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFreelancerResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeleteFreelancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) ActivateFreelancer(ctx context.Context, in *ActivateFreelancerRequest, opts ...grpc.CallOption) (*ActivateFreelancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateFreelancerResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_ActivateFreelancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeactivateFreelancer(ctx context.Context, in *DeactivateFreelancerRequest, opts ...grpc.CallOption) (*DeactivateFreelancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateFreelancerResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeactivateFreelancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) SaveFreelancerPhoto(ctx context.Context, in *SaveFreelancerPhotoRequest, opts ...grpc.CallOption) (*SaveFreelancerPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveFreelancerPhotoResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_SaveFreelancerPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) AddAdditionalCity(ctx context.Context, in *AddAdditionalCityRequest, opts ...grpc.CallOption) (*AddAdditionalCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAdditionalCityResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_AddAdditionalCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) AddAdditionalSpeciality(ctx context.Context, in *AddFreelancerAdditionalSpecialityRequest, opts ...grpc.CallOption) (*AddFreelancerAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFreelancerAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_AddAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeleteAdditionalCity(ctx context.Context, in *DeleteFreelancerAdditionalCityRequest, opts ...grpc.CallOption) (*DeleteFreelancerAdditionalCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFreelancerAdditionalCityResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeleteAdditionalCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeleteAdditionalSpeciality(ctx context.Context, in *DeleteFreelancerAdditionalSpecialityRequest, opts ...grpc.CallOption) (*DeleteFreelancerAdditionalSpecialityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFreelancerAdditionalSpecialityResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeleteAdditionalSpeciality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) AddRecommendation(ctx context.Context, in *AddRecommendationRequest, opts ...grpc.CallOption) (*AddRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecommendationResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_AddRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeleteRecommendation(ctx context.Context, in *DeleteRecommendationRequest, opts ...grpc.CallOption) (*DeleteRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecommendationResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeleteRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) ChangeRecommendationSort(ctx context.Context, in *ChangeRecommendationSortRequest, opts ...grpc.CallOption) (*ChangeRecommendationSortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeRecommendationSortResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_ChangeRecommendationSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) AddPriceList(ctx context.Context, in *AddPriceListRequest, opts ...grpc.CallOption) (*AddPriceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPriceListResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_AddPriceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeletePriceList(ctx context.Context, in *DeletePriceListRequest, opts ...grpc.CallOption) (*DeletePriceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePriceListResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeletePriceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_AddNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerAdditionalSpecialities(ctx context.Context, in *GetFreelancerAdditionalSpecialitiesRequest, opts ...grpc.CallOption) (*GetFreelancerAdditionalSpecialitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerAdditionalSpecialitiesResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerAdditionalSpecialities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerAdditionalCities(ctx context.Context, in *GetFreelancerAdditionalCitiesRequest, opts ...grpc.CallOption) (*GetFreelancerAdditionalCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerAdditionalCitiesResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerAdditionalCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerCooperationTypes(ctx context.Context, in *GetFreelancerCooperationTypesRequest, opts ...grpc.CallOption) (*GetFreelancerCooperationTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerCooperationTypesResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerCooperationTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerPriceList(ctx context.Context, in *GetFreelancerPriceListRequest, opts ...grpc.CallOption) (*GetFreelancerPriceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerPriceListResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerPriceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerRecommendations(ctx context.Context, in *GetFreelancerRecommendationsRequest, opts ...grpc.CallOption) (*GetFreelancerRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerRecommendationsResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freelancerAdminServiceClient) GetFreelancerSocialNetworks(ctx context.Context, in *GetFreelancerSocialNetworksRequest, opts ...grpc.CallOption) (*GetFreelancerSocialNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreelancerSocialNetworksResponse)
	err := c.cc.Invoke(ctx, FreelancerAdminService_GetFreelancerSocialNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreelancerAdminServiceServer is the server API for FreelancerAdminService service.
// All implementations should embed UnimplementedFreelancerAdminServiceServer
// for forward compatibility.
//
// -------------- Сервис по работе с докторов ---------------
type FreelancerAdminServiceServer interface {
	GetFreelancers(context.Context, *GetFreelancersRequest) (*GetFreelancersResponse, error)
	SortFreelancers(context.Context, *SortFreelancersRequest) (*SortFreelancersResponse, error)
	SearchFreelancers(context.Context, *SearchFreelancersRequest) (*SearchFreelancersResponse, error)
	GetFreelancerByID(context.Context, *GetFreelancerByIDRequest) (*GetFreelancerByIDResponse, error)
	UpdateFreelancer(context.Context, *UpdateFreelancerRequest) (*UpdateFreelancerResponse, error)
	DeleteFreelancer(context.Context, *DeleteFreelancerRequest) (*DeleteFreelancerResponse, error)
	ActivateFreelancer(context.Context, *ActivateFreelancerRequest) (*ActivateFreelancerResponse, error)
	DeactivateFreelancer(context.Context, *DeactivateFreelancerRequest) (*DeactivateFreelancerResponse, error)
	SaveFreelancerPhoto(context.Context, *SaveFreelancerPhotoRequest) (*SaveFreelancerPhotoResponse, error)
	AddAdditionalCity(context.Context, *AddAdditionalCityRequest) (*AddAdditionalCityResponse, error)
	AddAdditionalSpeciality(context.Context, *AddFreelancerAdditionalSpecialityRequest) (*AddFreelancerAdditionalSpecialityResponse, error)
	DeleteAdditionalCity(context.Context, *DeleteFreelancerAdditionalCityRequest) (*DeleteFreelancerAdditionalCityResponse, error)
	DeleteAdditionalSpeciality(context.Context, *DeleteFreelancerAdditionalSpecialityRequest) (*DeleteFreelancerAdditionalSpecialityResponse, error)
	AddRecommendation(context.Context, *AddRecommendationRequest) (*AddRecommendationResponse, error)
	DeleteRecommendation(context.Context, *DeleteRecommendationRequest) (*DeleteRecommendationResponse, error)
	ChangeRecommendationSort(context.Context, *ChangeRecommendationSortRequest) (*ChangeRecommendationSortResponse, error)
	AddPriceList(context.Context, *AddPriceListRequest) (*AddPriceListResponse, error)
	DeletePriceList(context.Context, *DeletePriceListRequest) (*DeletePriceListResponse, error)
	AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	GetFreelancerAdditionalSpecialities(context.Context, *GetFreelancerAdditionalSpecialitiesRequest) (*GetFreelancerAdditionalSpecialitiesResponse, error)
	GetFreelancerAdditionalCities(context.Context, *GetFreelancerAdditionalCitiesRequest) (*GetFreelancerAdditionalCitiesResponse, error)
	GetFreelancerCooperationTypes(context.Context, *GetFreelancerCooperationTypesRequest) (*GetFreelancerCooperationTypesResponse, error)
	GetFreelancerPriceList(context.Context, *GetFreelancerPriceListRequest) (*GetFreelancerPriceListResponse, error)
	GetFreelancerRecommendations(context.Context, *GetFreelancerRecommendationsRequest) (*GetFreelancerRecommendationsResponse, error)
	GetFreelancerSocialNetworks(context.Context, *GetFreelancerSocialNetworksRequest) (*GetFreelancerSocialNetworksResponse, error)
}

// UnimplementedFreelancerAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFreelancerAdminServiceServer struct{}

func (UnimplementedFreelancerAdminServiceServer) GetFreelancers(context.Context, *GetFreelancersRequest) (*GetFreelancersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancers not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) SortFreelancers(context.Context, *SortFreelancersRequest) (*SortFreelancersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SortFreelancers not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) SearchFreelancers(context.Context, *SearchFreelancersRequest) (*SearchFreelancersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFreelancers not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerByID(context.Context, *GetFreelancerByIDRequest) (*GetFreelancerByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerByID not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) UpdateFreelancer(context.Context, *UpdateFreelancerRequest) (*UpdateFreelancerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFreelancer not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeleteFreelancer(context.Context, *DeleteFreelancerRequest) (*DeleteFreelancerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFreelancer not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) ActivateFreelancer(context.Context, *ActivateFreelancerRequest) (*ActivateFreelancerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateFreelancer not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeactivateFreelancer(context.Context, *DeactivateFreelancerRequest) (*DeactivateFreelancerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateFreelancer not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) SaveFreelancerPhoto(context.Context, *SaveFreelancerPhotoRequest) (*SaveFreelancerPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFreelancerPhoto not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) AddAdditionalCity(context.Context, *AddAdditionalCityRequest) (*AddAdditionalCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdditionalCity not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) AddAdditionalSpeciality(context.Context, *AddFreelancerAdditionalSpecialityRequest) (*AddFreelancerAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdditionalSpeciality not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeleteAdditionalCity(context.Context, *DeleteFreelancerAdditionalCityRequest) (*DeleteFreelancerAdditionalCityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdditionalCity not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeleteAdditionalSpeciality(context.Context, *DeleteFreelancerAdditionalSpecialityRequest) (*DeleteFreelancerAdditionalSpecialityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdditionalSpeciality not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) AddRecommendation(context.Context, *AddRecommendationRequest) (*AddRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecommendation not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeleteRecommendation(context.Context, *DeleteRecommendationRequest) (*DeleteRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecommendation not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) ChangeRecommendationSort(context.Context, *ChangeRecommendationSortRequest) (*ChangeRecommendationSortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeRecommendationSort not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) AddPriceList(context.Context, *AddPriceListRequest) (*AddPriceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPriceList not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeletePriceList(context.Context, *DeletePriceListRequest) (*DeletePriceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePriceList not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNetwork not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerAdditionalSpecialities(context.Context, *GetFreelancerAdditionalSpecialitiesRequest) (*GetFreelancerAdditionalSpecialitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerAdditionalSpecialities not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerAdditionalCities(context.Context, *GetFreelancerAdditionalCitiesRequest) (*GetFreelancerAdditionalCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerAdditionalCities not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerCooperationTypes(context.Context, *GetFreelancerCooperationTypesRequest) (*GetFreelancerCooperationTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerCooperationTypes not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerPriceList(context.Context, *GetFreelancerPriceListRequest) (*GetFreelancerPriceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerPriceList not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerRecommendations(context.Context, *GetFreelancerRecommendationsRequest) (*GetFreelancerRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerRecommendations not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) GetFreelancerSocialNetworks(context.Context, *GetFreelancerSocialNetworksRequest) (*GetFreelancerSocialNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFreelancerSocialNetworks not implemented")
}
func (UnimplementedFreelancerAdminServiceServer) testEmbeddedByValue() {}

// UnsafeFreelancerAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreelancerAdminServiceServer will
// result in compilation errors.
type UnsafeFreelancerAdminServiceServer interface {
	mustEmbedUnimplementedFreelancerAdminServiceServer()
}

func RegisterFreelancerAdminServiceServer(s grpc.ServiceRegistrar, srv FreelancerAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedFreelancerAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FreelancerAdminService_ServiceDesc, srv)
}

func _FreelancerAdminService_GetFreelancers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancers(ctx, req.(*GetFreelancersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_SortFreelancers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortFreelancersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).SortFreelancers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_SortFreelancers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).SortFreelancers(ctx, req.(*SortFreelancersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_SearchFreelancers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFreelancersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).SearchFreelancers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_SearchFreelancers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).SearchFreelancers(ctx, req.(*SearchFreelancersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerByID(ctx, req.(*GetFreelancerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_UpdateFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFreelancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).UpdateFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_UpdateFreelancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).UpdateFreelancer(ctx, req.(*UpdateFreelancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeleteFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFreelancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeleteFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeleteFreelancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeleteFreelancer(ctx, req.(*DeleteFreelancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_ActivateFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateFreelancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).ActivateFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_ActivateFreelancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).ActivateFreelancer(ctx, req.(*ActivateFreelancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeactivateFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateFreelancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeactivateFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeactivateFreelancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeactivateFreelancer(ctx, req.(*DeactivateFreelancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_SaveFreelancerPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFreelancerPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).SaveFreelancerPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_SaveFreelancerPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).SaveFreelancerPhoto(ctx, req.(*SaveFreelancerPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_AddAdditionalCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdditionalCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).AddAdditionalCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_AddAdditionalCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).AddAdditionalCity(ctx, req.(*AddAdditionalCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_AddAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFreelancerAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).AddAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_AddAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).AddAdditionalSpeciality(ctx, req.(*AddFreelancerAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeleteAdditionalCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFreelancerAdditionalCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeleteAdditionalCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeleteAdditionalCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeleteAdditionalCity(ctx, req.(*DeleteFreelancerAdditionalCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeleteAdditionalSpeciality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFreelancerAdditionalSpecialityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeleteAdditionalSpeciality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeleteAdditionalSpeciality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeleteAdditionalSpeciality(ctx, req.(*DeleteFreelancerAdditionalSpecialityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_AddRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).AddRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_AddRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).AddRecommendation(ctx, req.(*AddRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeleteRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeleteRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeleteRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeleteRecommendation(ctx, req.(*DeleteRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_ChangeRecommendationSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRecommendationSortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).ChangeRecommendationSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_ChangeRecommendationSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).ChangeRecommendationSort(ctx, req.(*ChangeRecommendationSortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_AddPriceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPriceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).AddPriceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_AddPriceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).AddPriceList(ctx, req.(*AddPriceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeletePriceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePriceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeletePriceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeletePriceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeletePriceList(ctx, req.(*DeletePriceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_AddNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).AddNetwork(ctx, req.(*AddNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerAdditionalSpecialities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerAdditionalSpecialitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerAdditionalSpecialities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerAdditionalSpecialities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerAdditionalSpecialities(ctx, req.(*GetFreelancerAdditionalSpecialitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerAdditionalCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerAdditionalCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerAdditionalCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerAdditionalCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerAdditionalCities(ctx, req.(*GetFreelancerAdditionalCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerCooperationTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerCooperationTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerCooperationTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerCooperationTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerCooperationTypes(ctx, req.(*GetFreelancerCooperationTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerPriceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerPriceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerPriceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerPriceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerPriceList(ctx, req.(*GetFreelancerPriceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerRecommendations(ctx, req.(*GetFreelancerRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreelancerAdminService_GetFreelancerSocialNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreelancerSocialNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreelancerAdminServiceServer).GetFreelancerSocialNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreelancerAdminService_GetFreelancerSocialNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreelancerAdminServiceServer).GetFreelancerSocialNetworks(ctx, req.(*GetFreelancerSocialNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FreelancerAdminService_ServiceDesc is the grpc.ServiceDesc for FreelancerAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FreelancerAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.freelancers.freelancer.v1.FreelancerAdminService",
	HandlerType: (*FreelancerAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFreelancers",
			Handler:    _FreelancerAdminService_GetFreelancers_Handler,
		},
		{
			MethodName: "SortFreelancers",
			Handler:    _FreelancerAdminService_SortFreelancers_Handler,
		},
		{
			MethodName: "SearchFreelancers",
			Handler:    _FreelancerAdminService_SearchFreelancers_Handler,
		},
		{
			MethodName: "GetFreelancerByID",
			Handler:    _FreelancerAdminService_GetFreelancerByID_Handler,
		},
		{
			MethodName: "UpdateFreelancer",
			Handler:    _FreelancerAdminService_UpdateFreelancer_Handler,
		},
		{
			MethodName: "DeleteFreelancer",
			Handler:    _FreelancerAdminService_DeleteFreelancer_Handler,
		},
		{
			MethodName: "ActivateFreelancer",
			Handler:    _FreelancerAdminService_ActivateFreelancer_Handler,
		},
		{
			MethodName: "DeactivateFreelancer",
			Handler:    _FreelancerAdminService_DeactivateFreelancer_Handler,
		},
		{
			MethodName: "SaveFreelancerPhoto",
			Handler:    _FreelancerAdminService_SaveFreelancerPhoto_Handler,
		},
		{
			MethodName: "AddAdditionalCity",
			Handler:    _FreelancerAdminService_AddAdditionalCity_Handler,
		},
		{
			MethodName: "AddAdditionalSpeciality",
			Handler:    _FreelancerAdminService_AddAdditionalSpeciality_Handler,
		},
		{
			MethodName: "DeleteAdditionalCity",
			Handler:    _FreelancerAdminService_DeleteAdditionalCity_Handler,
		},
		{
			MethodName: "DeleteAdditionalSpeciality",
			Handler:    _FreelancerAdminService_DeleteAdditionalSpeciality_Handler,
		},
		{
			MethodName: "AddRecommendation",
			Handler:    _FreelancerAdminService_AddRecommendation_Handler,
		},
		{
			MethodName: "DeleteRecommendation",
			Handler:    _FreelancerAdminService_DeleteRecommendation_Handler,
		},
		{
			MethodName: "ChangeRecommendationSort",
			Handler:    _FreelancerAdminService_ChangeRecommendationSort_Handler,
		},
		{
			MethodName: "AddPriceList",
			Handler:    _FreelancerAdminService_AddPriceList_Handler,
		},
		{
			MethodName: "DeletePriceList",
			Handler:    _FreelancerAdminService_DeletePriceList_Handler,
		},
		{
			MethodName: "AddNetwork",
			Handler:    _FreelancerAdminService_AddNetwork_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _FreelancerAdminService_DeleteNetwork_Handler,
		},
		{
			MethodName: "GetFreelancerAdditionalSpecialities",
			Handler:    _FreelancerAdminService_GetFreelancerAdditionalSpecialities_Handler,
		},
		{
			MethodName: "GetFreelancerAdditionalCities",
			Handler:    _FreelancerAdminService_GetFreelancerAdditionalCities_Handler,
		},
		{
			MethodName: "GetFreelancerCooperationTypes",
			Handler:    _FreelancerAdminService_GetFreelancerCooperationTypes_Handler,
		},
		{
			MethodName: "GetFreelancerPriceList",
			Handler:    _FreelancerAdminService_GetFreelancerPriceList_Handler,
		},
		{
			MethodName: "GetFreelancerRecommendations",
			Handler:    _FreelancerAdminService_GetFreelancerRecommendations_Handler,
		},
		{
			MethodName: "GetFreelancerSocialNetworks",
			Handler:    _FreelancerAdminService_GetFreelancerSocialNetworks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/freelancers/freelancer/v1/admin.proto",
}
