// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/blogs/v1/admin.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogsRequest) Reset() {
	*x = GetBlogsRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsRequest) ProtoMessage() {}

func (x *GetBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GetBlogsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Blogs         []*GetBlogsResponse_Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogsResponse) Reset() {
	*x = GetBlogsResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsResponse) ProtoMessage() {}

func (x *GetBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlogsResponse) GetBlogs() []*GetBlogsResponse_Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetBlogByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogByIDRequest) Reset() {
	*x = GetBlogByIDRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIDRequest) ProtoMessage() {}

func (x *GetBlogByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBlogByIDRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlogByIDRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type GetBlogByIDResponse struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	BlogId            string                          `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Slug              string                          `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title             string                          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body              string                          `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsActive          bool                            `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PreviewText       string                          `protobuf:"bytes,6,opt,name=preview_text,json=previewText,proto3" json:"preview_text,omitempty"`
	SocietyPreview    string                          `protobuf:"bytes,7,opt,name=society_preview,json=societyPreview,proto3" json:"society_preview,omitempty"`
	AdditionalSeoText string                          `protobuf:"bytes,8,opt,name=additional_seo_text,json=additionalSeoText,proto3" json:"additional_seo_text,omitempty"`
	OrderingNumber    int64                           `protobuf:"varint,9,opt,name=ordering_number,json=orderingNumber,proto3" json:"ordering_number,omitempty"`
	Doctor            *GetBlogByIDResponse_Doctor     `protobuf:"bytes,10,opt,name=doctor,proto3" json:"doctor,omitempty"`
	Categories        []*GetBlogByIDResponse_Category `protobuf:"bytes,11,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBlogByIDResponse) Reset() {
	*x = GetBlogByIDResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIDResponse) ProtoMessage() {}

func (x *GetBlogByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIDResponse.ProtoReflect.Descriptor instead.
func (*GetBlogByIDResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogByIDResponse) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetBlogByIDResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetBlogByIDResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogByIDResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetBlogByIDResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetBlogByIDResponse) GetPreviewText() string {
	if x != nil {
		return x.PreviewText
	}
	return ""
}

func (x *GetBlogByIDResponse) GetSocietyPreview() string {
	if x != nil {
		return x.SocietyPreview
	}
	return ""
}

func (x *GetBlogByIDResponse) GetAdditionalSeoText() string {
	if x != nil {
		return x.AdditionalSeoText
	}
	return ""
}

func (x *GetBlogByIDResponse) GetOrderingNumber() int64 {
	if x != nil {
		return x.OrderingNumber
	}
	return 0
}

func (x *GetBlogByIDResponse) GetDoctor() *GetBlogByIDResponse_Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

func (x *GetBlogByIDResponse) GetCategories() []*GetBlogByIDResponse_Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateDraftBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftBlogRequest) Reset() {
	*x = CreateDraftBlogRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftBlogRequest) ProtoMessage() {}

func (x *CreateDraftBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateDraftBlogRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDraftBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDraftBlogRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateDraftBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftBlogResponse) Reset() {
	*x = CreateDraftBlogResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftBlogResponse) ProtoMessage() {}

func (x *CreateDraftBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateDraftBlogResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDraftBlogResponse) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type UpdateDraftBlogRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlogId            string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Slug              string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body              string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsActive          bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PreviewText       string                 `protobuf:"bytes,6,opt,name=preview_text,json=previewText,proto3" json:"preview_text,omitempty"`
	SocietyPreview    string                 `protobuf:"bytes,7,opt,name=society_preview,json=societyPreview,proto3" json:"society_preview,omitempty"`
	AdditionalSeoText string                 `protobuf:"bytes,8,opt,name=additional_seo_text,json=additionalSeoText,proto3" json:"additional_seo_text,omitempty"`
	OrderingNumber    int64                  `protobuf:"varint,9,opt,name=ordering_number,json=orderingNumber,proto3" json:"ordering_number,omitempty"`
	DoctorId          int64                  `protobuf:"varint,10,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDraftBlogRequest) Reset() {
	*x = UpdateDraftBlogRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDraftBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDraftBlogRequest) ProtoMessage() {}

func (x *UpdateDraftBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDraftBlogRequest.ProtoReflect.Descriptor instead.
func (*UpdateDraftBlogRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDraftBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateDraftBlogRequest) GetPreviewText() string {
	if x != nil {
		return x.PreviewText
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetSocietyPreview() string {
	if x != nil {
		return x.SocietyPreview
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetAdditionalSeoText() string {
	if x != nil {
		return x.AdditionalSeoText
	}
	return ""
}

func (x *UpdateDraftBlogRequest) GetOrderingNumber() int64 {
	if x != nil {
		return x.OrderingNumber
	}
	return 0
}

func (x *UpdateDraftBlogRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type UpdateDraftBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDraftBlogResponse) Reset() {
	*x = UpdateDraftBlogResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDraftBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDraftBlogResponse) ProtoMessage() {}

func (x *UpdateDraftBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDraftBlogResponse.ProtoReflect.Descriptor instead.
func (*UpdateDraftBlogResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{7}
}

type SaveBlogImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	ImageData     string                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // файл в строке base64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBlogImageRequest) Reset() {
	*x = SaveBlogImageRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBlogImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBlogImageRequest) ProtoMessage() {}

func (x *SaveBlogImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBlogImageRequest.ProtoReflect.Descriptor instead.
func (*SaveBlogImageRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *SaveBlogImageRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *SaveBlogImageRequest) GetImageData() string {
	if x != nil {
		return x.ImageData
	}
	return ""
}

type SaveBlogImageResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Image         *SaveBlogImageResponse_Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBlogImageResponse) Reset() {
	*x = SaveBlogImageResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBlogImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBlogImageResponse) ProtoMessage() {}

func (x *SaveBlogImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBlogImageResponse.ProtoReflect.Descriptor instead.
func (*SaveBlogImageResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *SaveBlogImageResponse) GetImage() *SaveBlogImageResponse_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type DeleteBlogImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogImageRequest) Reset() {
	*x = DeleteBlogImageRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogImageRequest) ProtoMessage() {}

func (x *DeleteBlogImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogImageRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBlogImageRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *DeleteBlogImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type DeleteBlogImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogImageResponse) Reset() {
	*x = DeleteBlogImageResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogImageResponse) ProtoMessage() {}

func (x *DeleteBlogImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogImageResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogImageResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{11}
}

type PublishBlogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlogId         string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	PrimaryImageId *string                `protobuf:"bytes,2,opt,name=primary_image_id,json=primaryImageId,proto3,oneof" json:"primary_image_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishBlogRequest) Reset() {
	*x = PublishBlogRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogRequest) ProtoMessage() {}

func (x *PublishBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogRequest.ProtoReflect.Descriptor instead.
func (*PublishBlogRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *PublishBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *PublishBlogRequest) GetPrimaryImageId() string {
	if x != nil && x.PrimaryImageId != nil {
		return *x.PrimaryImageId
	}
	return ""
}

type PublishBlogResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Errors        []*PublishBlogResponse_ValidationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBlogResponse) Reset() {
	*x = PublishBlogResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogResponse) ProtoMessage() {}

func (x *PublishBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogResponse.ProtoReflect.Descriptor instead.
func (*PublishBlogResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *PublishBlogResponse) GetErrors() []*PublishBlogResponse_ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type UnPublishBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnPublishBlogRequest) Reset() {
	*x = UnPublishBlogRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnPublishBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPublishBlogRequest) ProtoMessage() {}

func (x *UnPublishBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPublishBlogRequest.ProtoReflect.Descriptor instead.
func (*UnPublishBlogRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *UnPublishBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type UnPublishBlogResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Errors        []*UnPublishBlogResponse_ValidationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnPublishBlogResponse) Reset() {
	*x = UnPublishBlogResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnPublishBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPublishBlogResponse) ProtoMessage() {}

func (x *UnPublishBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPublishBlogResponse.ProtoReflect.Descriptor instead.
func (*UnPublishBlogResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UnPublishBlogResponse) GetErrors() []*UnPublishBlogResponse_ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type AddBlogCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlogCategoryRequest) Reset() {
	*x = AddBlogCategoryRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlogCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlogCategoryRequest) ProtoMessage() {}

func (x *AddBlogCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlogCategoryRequest.ProtoReflect.Descriptor instead.
func (*AddBlogCategoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AddBlogCategoryRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *AddBlogCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type DeleteBlogCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogCategoryRequest) Reset() {
	*x = DeleteBlogCategoryRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogCategoryRequest) ProtoMessage() {}

func (x *DeleteBlogCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogCategoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteBlogCategoryRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *DeleteBlogCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetBlogCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogCategoriesRequest) Reset() {
	*x = GetBlogCategoriesRequest{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogCategoriesRequest) ProtoMessage() {}

func (x *GetBlogCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetBlogCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{18}
}

type AddBlogCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlogCategoryResponse) Reset() {
	*x = AddBlogCategoryResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlogCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlogCategoryResponse) ProtoMessage() {}

func (x *AddBlogCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlogCategoryResponse.ProtoReflect.Descriptor instead.
func (*AddBlogCategoryResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{19}
}

type DeleteBlogCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogCategoryResponse) Reset() {
	*x = DeleteBlogCategoryResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogCategoryResponse) ProtoMessage() {}

func (x *DeleteBlogCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogCategoryResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{20}
}

type GetBlogCategoriesResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Categories    []*GetBlogCategoriesResponse_Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogCategoriesResponse) Reset() {
	*x = GetBlogCategoriesResponse{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogCategoriesResponse) ProtoMessage() {}

func (x *GetBlogCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetBlogCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *GetBlogCategoriesResponse) GetCategories() []*GetBlogCategoriesResponse_Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetBlogsResponse_Blog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlogId         string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IsActive       bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	OrderingNumber int64                  `protobuf:"varint,4,opt,name=ordering_number,json=orderingNumber,proto3" json:"ordering_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlogsResponse_Blog) Reset() {
	*x = GetBlogsResponse_Blog{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsResponse_Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsResponse_Blog) ProtoMessage() {}

func (x *GetBlogsResponse_Blog) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsResponse_Blog.ProtoReflect.Descriptor instead.
func (*GetBlogsResponse_Blog) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetBlogsResponse_Blog) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetBlogsResponse_Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogsResponse_Blog) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetBlogsResponse_Blog) GetOrderingNumber() int64 {
	if x != nil {
		return x.OrderingNumber
	}
	return 0
}

type GetBlogByIDResponse_Doctor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int64                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName    string                 `protobuf:"bytes,2,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogByIDResponse_Doctor) Reset() {
	*x = GetBlogByIDResponse_Doctor{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIDResponse_Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIDResponse_Doctor) ProtoMessage() {}

func (x *GetBlogByIDResponse_Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIDResponse_Doctor.ProtoReflect.Descriptor instead.
func (*GetBlogByIDResponse_Doctor) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetBlogByIDResponse_Doctor) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *GetBlogByIDResponse_Doctor) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

type GetBlogByIDResponse_Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogByIDResponse_Category) Reset() {
	*x = GetBlogByIDResponse_Category{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIDResponse_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIDResponse_Category) ProtoMessage() {}

func (x *GetBlogByIDResponse_Category) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIDResponse_Category.ProtoReflect.Descriptor instead.
func (*GetBlogByIDResponse_Category) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetBlogByIDResponse_Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBlogByIDResponse_Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SaveBlogImageResponse_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBlogImageResponse_Image) Reset() {
	*x = SaveBlogImageResponse_Image{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBlogImageResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBlogImageResponse_Image) ProtoMessage() {}

func (x *SaveBlogImageResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBlogImageResponse_Image.ProtoReflect.Descriptor instead.
func (*SaveBlogImageResponse_Image) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SaveBlogImageResponse_Image) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *SaveBlogImageResponse_Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type PublishBlogResponse_ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBlogResponse_ValidationError) Reset() {
	*x = PublishBlogResponse_ValidationError{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBlogResponse_ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogResponse_ValidationError) ProtoMessage() {}

func (x *PublishBlogResponse_ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogResponse_ValidationError.ProtoReflect.Descriptor instead.
func (*PublishBlogResponse_ValidationError) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{13, 0}
}

func (x *PublishBlogResponse_ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *PublishBlogResponse_ValidationError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UnPublishBlogResponse_ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnPublishBlogResponse_ValidationError) Reset() {
	*x = UnPublishBlogResponse_ValidationError{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnPublishBlogResponse_ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPublishBlogResponse_ValidationError) ProtoMessage() {}

func (x *UnPublishBlogResponse_ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPublishBlogResponse_ValidationError.ProtoReflect.Descriptor instead.
func (*UnPublishBlogResponse_ValidationError) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{15, 0}
}

func (x *UnPublishBlogResponse_ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UnPublishBlogResponse_ValidationError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetBlogCategoriesResponse_Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogCategoriesResponse_Category) Reset() {
	*x = GetBlogCategoriesResponse_Category{}
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogCategoriesResponse_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogCategoriesResponse_Category) ProtoMessage() {}

func (x *GetBlogCategoriesResponse_Category) ProtoReflect() protoreflect.Message {
	mi := &file_admin_blogs_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogCategoriesResponse_Category.ProtoReflect.Descriptor instead.
func (*GetBlogCategoriesResponse_Category) Descriptor() ([]byte, []int) {
	return file_admin_blogs_v1_admin_proto_rawDescGZIP(), []int{21, 0}
}

func (x *GetBlogCategoriesResponse_Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBlogCategoriesResponse_Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_admin_blogs_v1_admin_proto protoreflect.FileDescriptor

const file_admin_blogs_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aadmin/blogs/v1/admin.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x11\n" +
	"\x0fGetBlogsRequest\"\xbd\x01\n" +
	"\x10GetBlogsResponse\x12,\n" +
	"\x05blogs\x18\x01 \x03(\v2\x16.GetBlogsResponse.BlogR\x05blogs\x1a{\n" +
	"\x04Blog\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12'\n" +
	"\x0fordering_number\x18\x04 \x01(\x03R\x0eorderingNumber\"-\n" +
	"\x12GetBlogByIDRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\"\x9a\x04\n" +
	"\x13GetBlogByIDResponse\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12!\n" +
	"\fpreview_text\x18\x06 \x01(\tR\vpreviewText\x12'\n" +
	"\x0fsociety_preview\x18\a \x01(\tR\x0esocietyPreview\x12.\n" +
	"\x13additional_seo_text\x18\b \x01(\tR\x11additionalSeoText\x12'\n" +
	"\x0fordering_number\x18\t \x01(\x03R\x0eorderingNumber\x123\n" +
	"\x06doctor\x18\n" +
	" \x01(\v2\x1b.GetBlogByIDResponse.DoctorR\x06doctor\x12=\n" +
	"\n" +
	"categories\x18\v \x03(\v2\x1d.GetBlogByIDResponse.CategoryR\n" +
	"categories\x1aF\n" +
	"\x06Doctor\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x03R\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x02 \x01(\tR\n" +
	"doctorName\x1a.\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x16CreateDraftBlogRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"2\n" +
	"\x17CreateDraftBlogResponse\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\"\xce\x02\n" +
	"\x16UpdateDraftBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12!\n" +
	"\fpreview_text\x18\x06 \x01(\tR\vpreviewText\x12'\n" +
	"\x0fsociety_preview\x18\a \x01(\tR\x0esocietyPreview\x12.\n" +
	"\x13additional_seo_text\x18\b \x01(\tR\x11additionalSeoText\x12'\n" +
	"\x0fordering_number\x18\t \x01(\x03R\x0eorderingNumber\x12\x1b\n" +
	"\tdoctor_id\x18\n" +
	" \x01(\x03R\bdoctorId\"\x19\n" +
	"\x17UpdateDraftBlogResponse\"N\n" +
	"\x14SaveBlogImageRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\tR\timageData\"\x8c\x01\n" +
	"\x15SaveBlogImageResponse\x122\n" +
	"\x05image\x18\x01 \x01(\v2\x1c.SaveBlogImageResponse.ImageR\x05image\x1a?\n" +
	"\x05Image\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"L\n" +
	"\x16DeleteBlogImageRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\"\x19\n" +
	"\x17DeleteBlogImageResponse\"q\n" +
	"\x12PublishBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12-\n" +
	"\x10primary_image_id\x18\x02 \x01(\tH\x00R\x0eprimaryImageId\x88\x01\x01B\x13\n" +
	"\x11_primary_image_id\"\x90\x01\n" +
	"\x13PublishBlogResponse\x12<\n" +
	"\x06errors\x18\x01 \x03(\v2$.PublishBlogResponse.ValidationErrorR\x06errors\x1a;\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"/\n" +
	"\x14UnPublishBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\"\x94\x01\n" +
	"\x15UnPublishBlogResponse\x12>\n" +
	"\x06errors\x18\x01 \x03(\v2&.UnPublishBlogResponse.ValidationErrorR\x06errors\x1a;\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"R\n" +
	"\x16AddBlogCategoryRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\"U\n" +
	"\x19DeleteBlogCategoryRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\"\x1a\n" +
	"\x18GetBlogCategoriesRequest\"\x19\n" +
	"\x17AddBlogCategoryResponse\"\x1c\n" +
	"\x1aDeleteBlogCategoryResponse\"\x90\x01\n" +
	"\x19GetBlogCategoriesResponse\x12C\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2#.GetBlogCategoriesResponse.CategoryR\n" +
	"categories\x1a.\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xac\x0e\n" +
	"\fAdminService\x12|\n" +
	"\bGetBlogs\x12\x10.GetBlogsRequest\x1a\x11.GetBlogsResponse\"K\x92A.\x12,Получение списка статей\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/admin/blog\x12\xa7\x01\n" +
	"\vGetBlogByID\x12\x13.GetBlogByIDRequest\x1a\x14.GetBlogByIDResponse\"m\x92AF\x12DПолучение информации о статье по ее ID\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/admin/blog/{blog_id}\x12\x9f\x01\n" +
	"\x0fCreateDraftBlog\x12\x17.CreateDraftBlogRequest\x1a\x18.CreateDraftBlogResponse\"Y\x92A2\x120Создание черновика статьи\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/admin/blog/create\x12\x9a\x01\n" +
	"\x0fUpdateDraftBlog\x12\x17.UpdateDraftBlogRequest\x1a\x18.UpdateDraftBlogResponse\"T\x92A#\x12!Обновление статьи\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/admin/blog/{blog_id}/update\x12\xb0\x01\n" +
	"\rSaveBlogImage\x12\x15.SaveBlogImageRequest\x1a\x16.SaveBlogImageResponse\"p\x92A;\x129Сохранение картинки для статьи\x82\xd3\xe4\x93\x02,:\x01*\"'/api/v1/admin/blog/{blog_id}/save_image\x12\xbf\x01\n" +
	"\x0fDeleteBlogImage\x12\x17.DeleteBlogImageRequest\x1a\x18.DeleteBlogImageResponse\"y\x92A7\x125Удаление картинки для статьи\x82\xd3\xe4\x93\x029:\x01*\"4/api/v1/admin/blog/{blog_id}/delete_image/{image_id}\x12\x8f\x01\n" +
	"\vPublishBlog\x12\x13.PublishBlogRequest\x1a\x14.PublishBlogResponse\"U\x92A#\x12!Публикация статьи\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/admin/blog/{blog_id}/publish\x12\xa7\x01\n" +
	"\rUnPublishBlog\x12\x15.UnPublishBlogRequest\x1a\x16.UnPublishBlogResponse\"g\x92A3\x121Снятие статьи с публикации\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/admin/blog/{blog_id}/unpublish\x12\xa9\x01\n" +
	"\x0fAddBlogCategory\x12\x17.AddBlogCategoryRequest\x1a\x18.AddBlogCategoryResponse\"c\x92A,\x12*Добавление тега статье\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/admin/blog/{blog_id}/add_category\x12\xb4\x01\n" +
	"\x12DeleteBlogCategory\x12\x1a.DeleteBlogCategoryRequest\x1a\x1b.DeleteBlogCategoryResponse\"e\x92A+\x12)Удаление тега у статьи\x82\xd3\xe4\x93\x021:\x01*\",/api/v1/admin/blog/{blog_id}/delete_category\x12\xa0\x01\n" +
	"\x11GetBlogCategories\x12\x19.GetBlogCategoriesRequest\x1a\x1a.GetBlogCategoriesResponse\"T\x92A,\x12*Получение тегов статей\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/admin/blog/categoriesB\x14Z\x12api/admin/blogs/v1b\x06proto3"

var (
	file_admin_blogs_v1_admin_proto_rawDescOnce sync.Once
	file_admin_blogs_v1_admin_proto_rawDescData []byte
)

func file_admin_blogs_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_blogs_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_blogs_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_blogs_v1_admin_proto_rawDesc), len(file_admin_blogs_v1_admin_proto_rawDesc)))
	})
	return file_admin_blogs_v1_admin_proto_rawDescData
}

var file_admin_blogs_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_admin_blogs_v1_admin_proto_goTypes = []any{
	(*GetBlogsRequest)(nil),                       // 0: GetBlogsRequest
	(*GetBlogsResponse)(nil),                      // 1: GetBlogsResponse
	(*GetBlogByIDRequest)(nil),                    // 2: GetBlogByIDRequest
	(*GetBlogByIDResponse)(nil),                   // 3: GetBlogByIDResponse
	(*CreateDraftBlogRequest)(nil),                // 4: CreateDraftBlogRequest
	(*CreateDraftBlogResponse)(nil),               // 5: CreateDraftBlogResponse
	(*UpdateDraftBlogRequest)(nil),                // 6: UpdateDraftBlogRequest
	(*UpdateDraftBlogResponse)(nil),               // 7: UpdateDraftBlogResponse
	(*SaveBlogImageRequest)(nil),                  // 8: SaveBlogImageRequest
	(*SaveBlogImageResponse)(nil),                 // 9: SaveBlogImageResponse
	(*DeleteBlogImageRequest)(nil),                // 10: DeleteBlogImageRequest
	(*DeleteBlogImageResponse)(nil),               // 11: DeleteBlogImageResponse
	(*PublishBlogRequest)(nil),                    // 12: PublishBlogRequest
	(*PublishBlogResponse)(nil),                   // 13: PublishBlogResponse
	(*UnPublishBlogRequest)(nil),                  // 14: UnPublishBlogRequest
	(*UnPublishBlogResponse)(nil),                 // 15: UnPublishBlogResponse
	(*AddBlogCategoryRequest)(nil),                // 16: AddBlogCategoryRequest
	(*DeleteBlogCategoryRequest)(nil),             // 17: DeleteBlogCategoryRequest
	(*GetBlogCategoriesRequest)(nil),              // 18: GetBlogCategoriesRequest
	(*AddBlogCategoryResponse)(nil),               // 19: AddBlogCategoryResponse
	(*DeleteBlogCategoryResponse)(nil),            // 20: DeleteBlogCategoryResponse
	(*GetBlogCategoriesResponse)(nil),             // 21: GetBlogCategoriesResponse
	(*GetBlogsResponse_Blog)(nil),                 // 22: GetBlogsResponse.Blog
	(*GetBlogByIDResponse_Doctor)(nil),            // 23: GetBlogByIDResponse.Doctor
	(*GetBlogByIDResponse_Category)(nil),          // 24: GetBlogByIDResponse.Category
	(*SaveBlogImageResponse_Image)(nil),           // 25: SaveBlogImageResponse.Image
	(*PublishBlogResponse_ValidationError)(nil),   // 26: PublishBlogResponse.ValidationError
	(*UnPublishBlogResponse_ValidationError)(nil), // 27: UnPublishBlogResponse.ValidationError
	(*GetBlogCategoriesResponse_Category)(nil),    // 28: GetBlogCategoriesResponse.Category
}
var file_admin_blogs_v1_admin_proto_depIdxs = []int32{
	22, // 0: GetBlogsResponse.blogs:type_name -> GetBlogsResponse.Blog
	23, // 1: GetBlogByIDResponse.doctor:type_name -> GetBlogByIDResponse.Doctor
	24, // 2: GetBlogByIDResponse.categories:type_name -> GetBlogByIDResponse.Category
	25, // 3: SaveBlogImageResponse.image:type_name -> SaveBlogImageResponse.Image
	26, // 4: PublishBlogResponse.errors:type_name -> PublishBlogResponse.ValidationError
	27, // 5: UnPublishBlogResponse.errors:type_name -> UnPublishBlogResponse.ValidationError
	28, // 6: GetBlogCategoriesResponse.categories:type_name -> GetBlogCategoriesResponse.Category
	0,  // 7: AdminService.GetBlogs:input_type -> GetBlogsRequest
	2,  // 8: AdminService.GetBlogByID:input_type -> GetBlogByIDRequest
	4,  // 9: AdminService.CreateDraftBlog:input_type -> CreateDraftBlogRequest
	6,  // 10: AdminService.UpdateDraftBlog:input_type -> UpdateDraftBlogRequest
	8,  // 11: AdminService.SaveBlogImage:input_type -> SaveBlogImageRequest
	10, // 12: AdminService.DeleteBlogImage:input_type -> DeleteBlogImageRequest
	12, // 13: AdminService.PublishBlog:input_type -> PublishBlogRequest
	14, // 14: AdminService.UnPublishBlog:input_type -> UnPublishBlogRequest
	16, // 15: AdminService.AddBlogCategory:input_type -> AddBlogCategoryRequest
	17, // 16: AdminService.DeleteBlogCategory:input_type -> DeleteBlogCategoryRequest
	18, // 17: AdminService.GetBlogCategories:input_type -> GetBlogCategoriesRequest
	1,  // 18: AdminService.GetBlogs:output_type -> GetBlogsResponse
	3,  // 19: AdminService.GetBlogByID:output_type -> GetBlogByIDResponse
	5,  // 20: AdminService.CreateDraftBlog:output_type -> CreateDraftBlogResponse
	7,  // 21: AdminService.UpdateDraftBlog:output_type -> UpdateDraftBlogResponse
	9,  // 22: AdminService.SaveBlogImage:output_type -> SaveBlogImageResponse
	11, // 23: AdminService.DeleteBlogImage:output_type -> DeleteBlogImageResponse
	13, // 24: AdminService.PublishBlog:output_type -> PublishBlogResponse
	15, // 25: AdminService.UnPublishBlog:output_type -> UnPublishBlogResponse
	19, // 26: AdminService.AddBlogCategory:output_type -> AddBlogCategoryResponse
	20, // 27: AdminService.DeleteBlogCategory:output_type -> DeleteBlogCategoryResponse
	21, // 28: AdminService.GetBlogCategories:output_type -> GetBlogCategoriesResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_blogs_v1_admin_proto_init() }
func file_admin_blogs_v1_admin_proto_init() {
	if File_admin_blogs_v1_admin_proto != nil {
		return
	}
	file_admin_blogs_v1_admin_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_blogs_v1_admin_proto_rawDesc), len(file_admin_blogs_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_blogs_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_blogs_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_blogs_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_blogs_v1_admin_proto = out.File
	file_admin_blogs_v1_admin_proto_goTypes = nil
	file_admin_blogs_v1_admin_proto_depIdxs = nil
}
