name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      run: |
        echo "Deploying to production..."
        
        # Подключение к серверу и выполнение команд
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/medblogers_base
          git pull 
          docker-compose up --build -d
        EOF
        
        echo "Deployment completed!"

    - name: Health check
      run: |
        echo "Performing health check..."
        # curl -f http://your-app-url/health || exit 1
        echo "Health check passed!"
